stacks:
  - support
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  negative-invoices-processor-cloudformation:
    type: cloud-formation
    app: negative-invoices-processor
    parameters:
      templateStagePaths:
        CODE: negative-invoices-processor-CODE.template.json
        PROD: negative-invoices-processor-PROD.template.json
  negative-invoices-processor:
    type: aws-lambda
    parameters:
      fileName: negative-invoices-processor.zip
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
        - negative-invoices-processor-get-invoices-
        - negative-invoices-processor-check-for-active-sub-
        - negative-invoices-processor-get-payment-methods-
        - negative-invoices-processor-apply-credit-to-account-balance-
        - negative-invoices-processor-do-credit-balance-refund-
        - negative-invoices-processor-save-results-
        - negative-invoices-processor-detect-failures-
    dependencies: [negative-invoices-processor-cloudformation]
continuousDeployment:
  enabled: true
  stages: [CODE]
  filters:
    - branch: main
    - buildStatus: success
