stacks:
  - support
regions:
  - eu-west-1
allowedStages:
  - CSBX
  - PROD
deployments:
  write-off-unpaid-invoices-cloudformation:
    type: cloud-formation
    app: write-off-unpaid-invoices
    parameters:
      templateStagePaths:
        CSBX: write-off-unpaid-invoices-CSBX.template.json
        PROD: write-off-unpaid-invoices-PROD.template.json
  write-off-unpaid-invoices:
    type: aws-lambda
    parameters:
      fileName: write-off-unpaid-invoices.zip
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
        - write-off-invoice-
    dependencies: [write-off-unpaid-invoices-cloudformation]
