stacks:
  - support
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  salesforce-event-bus-cloudformation:
    type: cloud-formation
    app: salesforce-event-bus
    parameters:
      templateStagePaths:
        CODE: salesforce-event-bus-CODE.template.json
        PROD: salesforce-event-bus-PROD.template.json
