Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
      - DEV
    Default: CODE
  AppName:
    Type: String
    Default: payment-failure-comms

Conditions:
  IsProd: !Equals [ !Ref Stage, PROD ]

Mappings:
  StageMap:
    PROD:
      BrazeInstanceUrl: rest.fra-01.braze.eu
      BrazeAppGroup: DEV
      BrazeSecretsVersion: 9af74d40-b1a9-433b-b826-232af35f0cf6
    CODE:
      BrazeInstanceUrl: rest.fra-01.braze.eu
      BrazeAppGroup: DEV
      BrazeSecretsVersion: 9af74d40-b1a9-433b-b826-232af35f0cf6
    DEV:
      BrazeInstanceUrl: rest.fra-01.braze.eu
      BrazeAppGroup: DEV
      BrazeSecretsVersion: 9af74d40-b1a9-433b-b826-232af35f0cf6

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AppName}-${Stage}
      RetentionInDays: 90

  PaymentFailureCommsGateway:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: '2.0'
      Name: !Sub ${AppName}-${Stage}-ApiGateway
      StageName: !Sub ${Stage}

  PaymentFailureCommsLambda:
    Type: AWS::Serverless::Function
    DependsOn: LogGroup
    Properties:
      FunctionName: !Sub ${AppName}-${Stage}
      Handler: com.gu.payment_failure_comms.Handler
      Runtime: java8
      CodeUri:
        Bucket: support-service-lambdas-dist
        Key: !Sub membership/${Stage}/${AppName}/${AppName}.jar
      Timeout: 120
      MemorySize: 256
      Environment:
        Variables:
          brazeInstanceUrl: !FindInMap [ StageMap, !Ref Stage, BrazeInstanceUrl ]
          brazeBearerToken:
            !Sub
            - '{{resolve:secretsmanager:Braze/${BrazeAppGroup}/${AppName}:SecretString:bearerToken::${BrazeSecretsVersion}}}'
            - BrazeAppGroup: !FindInMap [ StageMap, !Ref Stage, BrazeAppGroup ]
              BrazeSecretsVersion: !FindInMap [ StageMap, !Ref Stage, BrazeSecretsVersion ]
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId:
              Ref: PaymentFailureCommsGateway
