packages:
  # lambdas
  - 'handlers/*'
  # shared code
  - 'modules/*'
  # cdk directory
  - 'cdk'
  # build generator
  - 'buildcheck'

catalog:
  zod: ^3.23.8
  typescript: ^5.6.3
  dayjs: ^1.11.13
  '@types/aws-lambda': ^8.10.147
  'source-map-support': ^0.5.21
  '@aws-sdk/client-cloudwatch': ^3.848.0
  '@aws-sdk/credential-providers': ^3.848.0
