packages:
  # lambdas
  - 'handlers/*'
  - 'handlers/*/lambda'
  # per lambda cdk
  - 'handlers/*/cdk'
  # shared code
  - 'modules/*'
  # cdk directory
  - 'cdk'
  - 'cdk/module'

catalog:
  zod: ^3.23.8
  typescript: ^5.6.3