packages:
  # lambdas
  - 'handlers/*'
  # shared code
  - 'modules/*'
  # cdk directory
  - 'cdk'
  # build generator
  - 'buildcheck'

allowBuilds:
  aws-sdk: true
  core-js: true
  esbuild: true
  protobufjs: true

catalog:
  zod: ^4.4.3
  typescript: "npm:@typescript/typescript6@^6.0.2"
  "@typescript/native": "npm:typescript@^7.0.2"
  "@aws-sdk/client-ssm": ^3.848.0,
  tsconfig-paths: ^4.2.0

overrides:
  typescript-eslint: ^8.63.0
  micromatch>braces: ^3.0.3
  cross-spawn: ^7.0.6
  "@babel/helpers@<7.26.10": ">=7.26.10"
  "brace-expansion@>=1.0.0 <=1.1.11": ^1.1.12
  "brace-expansion@>=2.0.0 <=2.0.1": ^2.0.2
  form-data: ^2.5.5
  flatted: ">=3.4.0"
  "path-to-regexp@>=8.0.0 <8.4.0": ^8.4.0
  "picomatch@>=4.0.0 <4.0.4": 4.0.4
  "picomatch@>=3.0.0 <3.0.2": 3.0.2
  "picomatch@<2.3.2": 2.3.2
  "@smithy/types": ^4.13.1
