AWSTemplateFormatVersion: "2010-09-09"
Description: Performs a Subject Access Requests against Zuora

Parameters:
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - PROD
            - CODE
        Default: CODE
    SarResultsBucket:
        Description: Bucket where sar results are uploaded to
        Type: String
        Default: baton-results

Resources:
    IdentityInvokeRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub "zuora-baton-lambda-role-${Stage}"
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          AWS: !Sub "arn:aws:iam::942464564246:root"
                      Action:
                          - sts:AssumeRole
            Path: /
            Policies:
                - PolicyName: LambdaPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                            - lambda:InvokeFunction
                            Resource: !GetAtt ZuoraBatonSarLambda.Arn
#    LambdaSecurityGroup:
#        Type: AWS::EC2::SecurityGroup
#        Properties:
#            GroupDescription: !Sub Security group for the zuora-sar-${Stage} lambdas
#            VpcId: !Ref VpcId

    ZuoraBatonSarLambda:
        Type: AWS::Lambda::Function
        Properties:
            Description: Initiates the PerformZuoraSarLambda and checks the status of Zuora SARs via S3
            FunctionName:
                !Sub zuora-baton-sar-lambda-${Stage}
            Code:
                S3Bucket: support-service-lambdas-dist
                S3Key: !Sub membership/${Stage}/zuora-sar/zuora-sar.jar
            Handler: com.gu.zuora.sar.Handler::handleSar
            Environment:
                Variables:
                  Stage: !Ref Stage
            MemorySize: 384
            Runtime: java8
            Timeout: 120
#            VpcConfig:
#                SecurityGroupIds: !Ref LambdaSecurityGroup
#                SubnetIds: !Ref VpcSubnets
            Policies:
                - PolicyName: S3ListPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                            - s3:ListBucket
                            Resource: !Sub arn:aws:s3:::${SarResultsBucket}
                - PolicyName: InvokeLambdaPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                            - lambda:InvokeFunction
                            Resource: !Ref PerformZuoraSarLambda

    PerformZuoraSarLambda:
        Type: AWS::Lambda::Function
        Properties:
            Description: Performs SAR to Zuora, writing results to S3
            FunctionName:
              !Sub zuora-baton-perform-sar-lambda-${Stage}
            Code:
                S3Bucket: support-service-lambdas-dist
                S3Key: !Sub membership/${Stage}/zuora-sar/zuora-sar.jar
            Handler: com.gu.zuora.sar.Handler::handlePerformSar
            Environment:
                Variables:
                    Stage: !Ref Stage
            MemorySize: 1024
            Runtime: java8
            Timeout: 900
#            VpcConfig:
#                SecurityGroupIds: !Ref LambdaSecurityGroup
#                SubnetIds: !Ref VpcSubnets
            Policies:
                - PolicyName: S3ListPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                                - s3:ListBucket
                            Resource: !Sub arn:aws:s3:::${SarResultsBucket}
                - PolicyName: S3ListPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                                - s3:PutObject
                                - s3:PutObjectAcl
                                - s3:GetObject
                            Resource: !Sub arn:aws:s3:::${SarResultsBucket}/zuora-results/${Stage}/*
