stacks:
- membership
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  cfn:
    type: cloud-formation
    app: zuora-sar
    parameters:
      templatePath: cfn.yaml

  zuora-sar:
    type: aws-lambda
    parameters:
      fileName: zuora-sar.jar
      bucket: support-service-lambdas-dist
      prefixStack: false
      functionNames: [zuora-baton-sar-lambda-, zuora-baton-perform-sar-lambda-]
    dependencies: [cfn]
