export const testQueryResponse = [
	{
		firstName: 'David',
		nextPaymentDate: '2025-02-27',
		paymentAmount: 1.23,
		paymentCurrency: 'GBP',
		paymentFrequency: 'Month',
		productName: 'GW',
		sfContactId: '0039E00001HiIGlQAN',
		zuoraSubName: 'A-S00886188', // Active sub in dev sandbox
		workEmail: 'david.pepper+david@guardian.co.uk',
		contactCountry: 'USA',
		sfBuyerContactMailingCountry: 'USA',
		sfBuyerContactOtherCountry: 'USA',
		sfRecipientContactMailingCountry: 'USA',
		sfRecipientContactOtherCountry: 'USA',
	},
	{
		firstName: 'Mary',
		nextPaymentDate: '2025-02-28',
		paymentAmount: 4.56,
		paymentCurrency: 'USD',
		paymentFrequency: 'Month',
		productName: 'Supporter Plus',
		sfContactId: '0039E00001HwhM9QAJ',
		zuoraSubName: 'A-S00886159', // Active subscription in dev sandbox
		workEmail: 'graham.hopgood@guardian.co.uk',
		contactCountry: 'US',
		sfBuyerContactMailingCountry: 'US',
		sfBuyerContactOtherCountry: 'US',
		sfRecipientContactMailingCountry: 'US',
		sfRecipientContactOtherCountry: 'US',
	},
	{
		firstName: 'Robert',
		nextPaymentDate: '2025-02-28',
		paymentAmount: 7.89,
		paymentCurrency: 'USD',
		paymentFrequency: 'Month',
		productName: 'Supporter Plus',
		sfContactId: '0039E00001lNoXrQAK',
		zuoraSubName: 'A-S00515481', // cancelled subscription in dev sandbox
		workEmail: 'david.pepper+3003+1@guardian.co.uk',
		contactCountry: 'Germany',
		sfBuyerContactMailingCountry: 'Germany',
		sfBuyerContactOtherCountry: 'Germany',
		sfRecipientContactMailingCountry: 'Germany',
		sfRecipientContactOtherCountry: 'Germany',
	},
];
