export const testQueryResponse = [
	{
		firstName: 'David',
		nextPaymentDate: '2025-02-27',
		paymentAmount: 1.23,
		paymentCurrency: 'GBP',
		paymentFrequency: 'Month',
		productName: 'GW',
		sfContactId: '0030J000022u2hrQAA',
		zuoraSubName: 'A-S02360124', // Active sub in prod
		workEmail: 'david.pepper@theguardian.com',
		contactCountry: 'united states of america',
		sfBuyerContactMailingCountry: 'united states of america',
		sfBuyerContactOtherCountry: 'united states of america',
		sfRecipientContactMailingCountry: 'united states of america',
		sfRecipientContactOtherCountry: 'united states of america',
	},
	{
		firstName: 'Graham',
		nextPaymentDate: '2025-02-28',
		paymentAmount: 4.56,
		paymentCurrency: 'USD',
		paymentFrequency: 'Month',
		productName: 'Supporter Plus',
		sfContactId: '0035I00000MQmHlQAL',
		zuoraSubName: 'A-S02360146', // Active subscription in prod
		workEmail: 'graham.hopgood@guardian.co.uk',
		contactCountry: 'United States',
		sfBuyerContactMailingCountry: 'United States',
		sfBuyerContactOtherCountry: 'United States',
		sfRecipientContactMailingCountry: 'United States',
		sfRecipientContactOtherCountry: 'United States',
	},
	// {
	// 	firstName: 'Robert',
	// 	nextPaymentDate: '2025-02-28',
	// 	paymentAmount: 7.89,
	// 	paymentCurrency: 'USD',
	// 	paymentFrequency: 'Month',
	// 	productName: 'Supporter Plus',
	// 	sfContactId: '0039E00001lNoXrQAK',
	// 	zuoraSubName: 'A-S00515481', // cancelled subscription in dev sandbox
	// 	workEmail: 'david.pepper+3003+1@guardian.co.uk',
	// 	contactCountry: 'Germany',
	// 	sfBuyerContactMailingCountry: 'Germany',
	// 	sfBuyerContactOtherCountry: 'Germany',
	// 	sfRecipientContactMailingCountry: 'Germany',
	// 	sfRecipientContactOtherCountry: 'Germany',
	// },
];
