package com.gu.holidaystopprocessor

import com.gu.salesforce.holiday_stops.SalesforceHolidayStopRequest.HolidayStopRequestId
import com.gu.salesforce.holiday_stops.SalesforceHolidayStopRequestActionedZuoraRef.{HolidayStopRequestActionedZuoraAmendmentCode, HolidayStopRequestActionedZuoraAmendmentPrice}

case class HolidayStopResponse(
  requestId: HolidayStopRequestId,
  amendmentCode: HolidayStopRequestActionedZuoraAmendmentCode,
  price: HolidayStopRequestActionedZuoraAmendmentPrice
)
