package com.gu.autoCancel

import com.gu.util.resthttp.Types.{ClientFailableOp, ClientSuccess}
import com.gu.util.resthttp.Types.GenericError
import com.gu.util.zuora.SubscriptionNumber
import com.gu.util.zuora.ZuoraGetInvoiceTransactions.{InvoiceItem, ItemisedInvoice}
import org.scalamock.scalatest.MockFactory
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

import java.time.LocalDate
import scala.concurrent.duration.DurationInt

class AutoCancelTest extends AnyFlatSpec with Matchers with MockFactory {

  "singleInvoiceNumber" should "use the one invoice generated by a cancellation order" in {
    AutoCancel.singleInvoiceNumber(Some(List("INV-000001"))) shouldBe Right("INV-000001")
  }

  it should "reject cancellation orders that do not identify exactly one invoice" in {
    AutoCancel.singleInvoiceNumber(None) shouldBe Left(
      GenericError("Zuora completed the cancellation order without returning invoice numbers"),
    )
    AutoCancel.singleInvoiceNumber(Some(Nil)) shouldBe Left(
      GenericError("Zuora completed the cancellation order without generating an invoice"),
    )
    AutoCancel.singleInvoiceNumber(Some(List("INV-000001", "INV-000002"))) shouldBe Left(
      GenericError("Zuora generated more than one invoice for a single subscription cancellation"),
    )
  }

  "orderDuration" should "leave time for the balance transfers after the order completes" in {
    AutoCancel.orderDuration(5.minutes.toMillis.toInt) shouldBe Some(3.minutes)
    AutoCancel.orderDuration(2.minutes.toMillis.toInt) shouldBe None
  }

  "applyCreditBalances" should "apply credit to multiple invoices" in {
    val subToCancel = SubscriptionNumber("s1")
    val applyCreditBalance = mockFunction[String, Double, String, ClientFailableOp[Unit]]
    applyCreditBalance.expects("invoice1", 12.34, "comment").returning(ClientSuccess(())).once()
    applyCreditBalance.expects("invoice2", 11.34, "comment").returning(ClientSuccess(())).once()
    val invoices = Seq(
      ItemisedInvoice(
        id = "invoice1",
        invoiceDate = LocalDate.of(2022, 1, 1),
        amount = 12.34,
        balance = 12.34,
        status = "Posted",
        invoiceItems = List(
          InvoiceItem(
            id = "item1",
            subscriptionName = subToCancel.value,
            serviceStartDate = LocalDate.of(2022, 1, 3),
            serviceEndDate = LocalDate.of(2022, 2, 2),
            chargeAmount = 12.34,
            chargeName = "chg",
            productName = "prd",
            taxAmount = 0,
          ),
        ),
      ),
      ItemisedInvoice(
        id = "invoice2",
        invoiceDate = LocalDate.of(2022, 1, 1),
        amount = 11.34,
        balance = 11.34,
        status = "Posted",
        invoiceItems = List(
          InvoiceItem(
            id = "item1",
            subscriptionName = "s2",
            serviceStartDate = LocalDate.of(2022, 1, 3),
            serviceEndDate = LocalDate.of(2022, 2, 2),
            chargeAmount = 11.34,
            chargeName = "chg",
            productName = "prd",
            taxAmount = 0,
          ),
        ),
      ),
    )
    AutoCancel.applyCreditBalances(applyCreditBalance)(subToCancel, invoices, "comment")
  }

  it should "apply partial credit to an invoice for multiple subscriptions" in {
    val subToCancel = SubscriptionNumber("s1")
    val applyCreditBalance = mockFunction[String, Double, String, ClientFailableOp[Unit]]
    applyCreditBalance.expects("invoice1", 6.87, "comment").returning(ClientSuccess(())).once()
    val invoices = Seq(
      ItemisedInvoice(
        id = "invoice1",
        invoiceDate = LocalDate.of(2022, 1, 1),
        amount = 12.34,
        balance = 12.34,
        status = "Posted",
        invoiceItems = List(
          InvoiceItem(
            id = "item1",
            subscriptionName = subToCancel.value,
            serviceStartDate = LocalDate.of(2022, 1, 3),
            serviceEndDate = LocalDate.of(2022, 2, 2),
            chargeAmount = 6.87,
            chargeName = "chg",
            productName = "prd",
            taxAmount = 0,
          ),
          InvoiceItem(
            id = "item2",
            subscriptionName = "s2",
            serviceStartDate = LocalDate.of(2022, 1, 4),
            serviceEndDate = LocalDate.of(2022, 2, 5),
            chargeAmount = 5.47,
            chargeName = "chg",
            productName = "prd",
            taxAmount = 0,
          ),
        ),
      ),
    )
    AutoCancel.applyCreditBalances(applyCreditBalance)(subToCancel, invoices, "comment")
  }

  it should "apply partial credit to an invoice for all items of the subscription to cancel" in {
    val subToCancel = SubscriptionNumber("s1")
    val applyCreditBalance = mockFunction[String, Double, String, ClientFailableOp[Unit]]
    applyCreditBalance.expects("invoice1", 11.09, "comment").returning(ClientSuccess(())).once()
    val invoices = Seq(
      ItemisedInvoice(
        id = "invoice1",
        invoiceDate = LocalDate.of(2022, 1, 1),
        amount = 12.34,
        balance = 12.34,
        status = "Posted",
        invoiceItems = List(
          InvoiceItem(
            id = "item1",
            subscriptionName = subToCancel.value,
            serviceStartDate = LocalDate.of(2022, 1, 3),
            serviceEndDate = LocalDate.of(2022, 2, 2),
            chargeAmount = 6.87,
            chargeName = "chg",
            productName = "prd",
            taxAmount = 0,
          ),
          InvoiceItem(
            id = "item3",
            subscriptionName = subToCancel.value,
            serviceStartDate = LocalDate.of(2022, 1, 3),
            serviceEndDate = LocalDate.of(2022, 2, 2),
            chargeAmount = 5.45,
            chargeName = "chg",
            productName = "prd",
            taxAmount = 0,
          ),
          InvoiceItem(
            id = "item4",
            subscriptionName = subToCancel.value,
            serviceStartDate = LocalDate.of(2022, 1, 3),
            serviceEndDate = LocalDate.of(2022, 2, 2),
            chargeAmount = -1.23,
            chargeName = "discount",
            productName = "discount",
            taxAmount = 0,
          ),
          InvoiceItem(
            id = "item2",
            subscriptionName = "s2",
            serviceStartDate = LocalDate.of(2022, 1, 4),
            serviceEndDate = LocalDate.of(2022, 2, 5),
            chargeAmount = 5.47,
            chargeName = "chg",
            productName = "prd",
            taxAmount = 0,
          ),
        ),
      ),
    )
    AutoCancel.applyCreditBalances(applyCreditBalance)(subToCancel, invoices, "comment")
  }

  it should "apply credit including items tax amount (not just charge amount)" in {
    val subToCancel = SubscriptionNumber("s1")
    val applyCreditBalance = mockFunction[String, Double, String, ClientFailableOp[Unit]]
    applyCreditBalance.expects("invoice1", 26.00, "comment").returning(ClientSuccess(())).once()
    val invoices = Seq(
      ItemisedInvoice(
        id = "invoice1",
        invoiceDate = LocalDate.of(2022, 1, 1),
        amount = 26.00,
        balance = 26.00,
        status = "Posted",
        invoiceItems = List(
          InvoiceItem(
            id = "item1",
            subscriptionName = subToCancel.value,
            serviceStartDate = LocalDate.of(2022, 1, 3),
            serviceEndDate = LocalDate.of(2022, 2, 2),
            chargeAmount = 12.34,
            chargeName = "chg",
            productName = "prd",
            taxAmount = 0.66,
          ),
          InvoiceItem(
            id = "item2",
            subscriptionName = subToCancel.value,
            serviceStartDate = LocalDate.of(2022, 1, 3),
            serviceEndDate = LocalDate.of(2022, 2, 2),
            chargeAmount = 12.34,
            chargeName = "chg",
            productName = "prd",
            taxAmount = 0.66,
          ),
        ),
      ),
    )
    AutoCancel.applyCreditBalances(applyCreditBalance)(subToCancel, invoices, "comment")
  }
}
