stacks:
- membership
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  cfn:
    type: cloud-formation
    app: sf-datalake-export
    parameters:
      templatePath: cfn.yaml
  sf-datalake-export:
    type: aws-lambda
    parameters:
      fileName: sf-datalake-export.jar
      bucket: support-service-lambdas-dist
      prefixStack: false
      functionNames:
      - sf-start-export-job-
      - sf-get-batch-state-
      - sf-download-batch-
      - sf-end-export-job-
      - sf-export-clean-bucket-
    dependencies: [cfn]
