Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - DEV
    Default: DEV

Mappings:
  StageMap:
    PROD:
      SalesforceUsername: EmailsToS3APIUser
      AppName: SFEmailsToS3
    DEV:
      SalesforceUsername: EmailsToS3APIUser
      AppName: AwsConnectorSandbox

Conditions:
  IsProd: !Equals [ !Ref Stage, PROD ]

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Retrieves emails from Salesforce and saves as Json to S3
      FunctionName: !Sub sf-emails-to-s3-exporter-${Stage}
      Handler: com.gu.sf_emails_to_s3_exporter.Handler::handleRequest
      CodeUri:
        Bucket: support-service-lambdas-dist
        Key: !Sub membership/${Stage}/sf-emails-to-s3-exporter/sf-emails-to-s3-exporter.jar
      MemorySize: 512
      Runtime: java8.al2
      Timeout: 900
      Environment:
        Variables:
          Stage: !Ref Stage
          bucketName: !Sub emails-from-sf-${Stage}
          sfApiVersion: v50.0
          sfAuthUrl:
            !Sub
            - '{{resolve:secretsmanager:${Stage}/Salesforce/ConnectedApp/${AppName}:SecretString:authUrl}}'
            - AppName: !FindInMap [ StageMap, !Ref Stage, AppName ]
          sfClientId:
            !Sub
            - '{{resolve:secretsmanager:${Stage}/Salesforce/ConnectedApp/${AppName}:SecretString:clientId}}'
            - AppName: !FindInMap [ StageMap, !Ref Stage, AppName ]
          sfClientSecret:
            !Sub
            - '{{resolve:secretsmanager:${Stage}/Salesforce/ConnectedApp/${AppName}:SecretString:clientSecret}}'
            - AppName: !FindInMap [ StageMap, !Ref Stage, AppName ]
          sfPassword:
            !Sub
            - '{{resolve:secretsmanager:${Stage}/Salesforce/User/${SalesforceUsername}:SecretString:sfPassword}}'
            - SalesforceUsername: !FindInMap [ StageMap, !Ref Stage, SalesforceUsername ]
          sfToken:
            !Sub
            - '{{resolve:secretsmanager:${Stage}/Salesforce/User/${SalesforceUsername}:SecretString:sfToken}}'
            - SalesforceUsername: !FindInMap [ StageMap, !Ref Stage, SalesforceUsername ]
          sfUsername:
            !Sub
            - '{{resolve:secretsmanager:${Stage}/Salesforce/User/${SalesforceUsername}:SecretString:sfUsername}}'
            - SalesforceUsername: !FindInMap [ StageMap, !Ref Stage, SalesforceUsername ]
      Policies:
        - Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource:
                - !Sub arn:aws:s3:::emails-from-sf-dev/*
        - Statement:
            - Effect: Allow
              Action: s3:PutObject
              Resource:
                - !Sub arn:aws:s3:::emails-from-sf-dev/*
        - Statement:
            - Effect: Allow
              Action: s3:ListBucket
              Resource:
                - !Sub arn:aws:s3:::emails-from-sf-dev/*
        - Statement:
            - Effect: Allow
              Action: s3:ListObjectV2
              Resource:
                - !Sub arn:aws:s3:::emails-from-sf-dev/*
        - Statement:
            - Sid: readDeployedArtefact
              Effect: Allow
              Action: s3:GetObject
              Resource:
                - arn:aws:s3::*:membership-dist/*