stacks:
  - membership
regions:
  - eu-west-1
deployments:

  cfn:
    type: cloud-formation
    app: export-emails-from-sf-to-s3
    parameters:
      templatePath: cfn.yaml

  export-emails-from-sf-to-s3:
    type: aws-lambda
    parameters:
      fileName: sf-emails-to-s3-exporter.jar
      bucket: support-service-lambdas-dist
      prefixStack: false
      functionNames:
        - export-emails-from-sf-to-s3-
    dependencies: [ cfn ]