stacks:
  - membership
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  sf-emails-to-s3-exporter-cloudformation:
    type: cloud-formation
    app: sf-emails-to-s3-exporter
    parameters:
      templateStagePaths:
        CODE: sf-emails-to-s3-exporter-CODE.template.json
        PROD: sf-emails-to-s3-exporter-PROD.template.json

  sf-emails-to-s3-exporter:
    type: aws-lambda
    parameters:
      fileName: sf-emails-to-s3-exporter.jar
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
        - sf-emails-to-s3-exporter-
    dependencies: [ sf-emails-to-s3-exporter-cloudformation ]
