stacks:
- support
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  stripe-disputes-webhook-cloudformation:
    type: cloud-formation
    #app: stripe-disputes-webhook
    app: stripe-disputes
    parameters:
      templateStagePaths:
        CODE: stripe-disputes-webhook-CODE.template.json
        PROD: stripe-disputes-webhook-PROD.template.json

  stripe-disputes-webhook:
    type: aws-lambda
    parameters:
      fileName: stripe-disputes-webhook.zip
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
      - stripe-disputes-webhook-
    dependencies: [stripe-disputes-webhook-cloudformation]
