import { GeneratedFile } from '../../steps/generate';
import { relativePath } from './notices';
import path from 'path';

// the generated file is named after this file.
// if you rename it, clean the snapshot first, then generate afterwards
const basename = path.basename(__filename);
if (!basename.endsWith('.ts')) {
	throw new Error(
		`Expected warning file name to end with .ts, got: ${basename}`,
	);
}
export const warningFileName = basename.slice(0, -3);

export function generateWarningFile(generatedFiles: string[]): GeneratedFile {
	return {
		relativePath: warningFileName,
		content: [
			'#',
			'# The files listed below are managed by buildgen.',
			'#',
			'# To make changes without failing the build:',
			'# 1. edit the build definition in buildgen/src/data/',
			'# 2. run `pnpm buildgen` at the root',
			'#',
			'# For further details, see buildgen/README.md',
			'#',
			'# Generated file list:',
			'#',
			...generatedFiles,
			warningFileName,
			'#',
			'# This file is generated by ' + relativePath(__filename),
		].join('\n'),
	};
}
