Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
      - DEV
    Default: CODE

Mappings:
  StageMap:
    PROD:
      Schedule: 'rate(30 minutes)'
      SalesforceStage: PROD
      IdentityStage: PROD
      SalesforceUsername: SoftOptInConsentSetterAPIUser
      AppName: TouchpointUpdate
      AppSecretsVersion: d338b761-cb81-4adf-aca4-163678e65a59
      SalesforceUserSecretsVersion: 31220691-ba9c-44b8-9483-d7939e30779e
      IdentityUserSecretsVersion: fe7df2e2-73a4-4d3f-9513-b8a6e7476aeb
    CODE:
      Schedule: 'rate(365 days)'
      SalesforceStage: CODE
      IdentityStage: CODE
      SalesforceUsername: SoftOptInConsentSetterAPIUser
      AppName: AwsConnectorSandbox
      AppSecretsVersion: 6fc22312-3ddb-4577-8a37-d58222a09db4
      SalesforceUserSecretsVersion: 9d7777f6-78d7-4ec3-8c93-d4912ce6316e
      IdentityUserSecretsVersion: ec3fd3ca-f237-4d2d-bbb2-0c9482e636c1
    DEV:
      Schedule: 'rate(365 days)'
      SalesforceStage: DEV
      IdentityStage: CODE
      SalesforceUsername: SoftOptInConsentSetterAPIUser
      AppName: AwsConnectorSandbox
      AppSecretsVersion: abaa595b-e6c8-4d13-81e0-2d02627536c7
      SalesforceUserSecretsVersion: 08036ddd-9fc0-43b1-b478-4023a936751e
      IdentityUserSecretsVersion: ec3fd3ca-f237-4d2d-bbb2-0c9482e636c1

Conditions:
  IsProd: !Equals [ !Ref Stage, PROD ]

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Updates Identity Soft Opt-In Consents upon Acquisition and Cancellation of Subscriptions in Salesforce
      FunctionName: !Sub soft-opt-in-consent-setter-${Stage}
      Handler: com.gu.soft_opt_in_consent_setter.Handler::handleRequest
      CodeUri:
        Bucket: support-service-lambdas-dist
        Key: !Sub membership/${Stage}/soft-opt-in-consent-setter/soft-opt-in-consent-setter.jar
      MemorySize: 512
      Runtime: java8.al2
      Timeout: 900
      Environment:
        Variables:
          Stage: !Ref Stage
          sfApiVersion: v46.0
          sfAuthUrl:
            !Sub
            - '{{resolve:secretsmanager:${SalesforceStage}/Salesforce/ConnectedApp/${AppName}:SecretString:authUrl::${AppSecretsVersion}}}'
            - SalesforceStage: !FindInMap [ StageMap, !Ref Stage, SalesforceStage ]
              AppName: !FindInMap [ StageMap, !Ref Stage, AppName ]
              AppSecretsVersion: !FindInMap [ StageMap, !Ref Stage, AppSecretsVersion ]
          sfClientId:
            !Sub
            - '{{resolve:secretsmanager:${SalesforceStage}/Salesforce/ConnectedApp/${AppName}:SecretString:clientId::${AppSecretsVersion}}}'
            - SalesforceStage: !FindInMap [ StageMap, !Ref Stage, SalesforceStage ]
              AppName: !FindInMap [ StageMap, !Ref Stage, AppName ]
              AppSecretsVersion: !FindInMap [ StageMap, !Ref Stage, AppSecretsVersion ]
          sfClientSecret:
            !Sub
            - '{{resolve:secretsmanager:${SalesforceStage}/Salesforce/ConnectedApp/${AppName}:SecretString:clientSecret::${AppSecretsVersion}}}'
            - SalesforceStage: !FindInMap [ StageMap, !Ref Stage, SalesforceStage ]
              AppName: !FindInMap [ StageMap, !Ref Stage, AppName ]
              AppSecretsVersion: !FindInMap [ StageMap, !Ref Stage, AppSecretsVersion ]
          sfPassword:
            !Sub
            - '{{resolve:secretsmanager:${SalesforceStage}/Salesforce/User/${SalesforceUsername}:SecretString:sfPassword::${SalesforceUserSecretsVersion}}}'
            - SalesforceStage: !FindInMap [ StageMap, !Ref Stage, SalesforceStage ]
              SalesforceUserSecretsVersion: !FindInMap [ StageMap, !Ref Stage, SalesforceUserSecretsVersion ]
              SalesforceUsername: !FindInMap [ StageMap, !Ref Stage, SalesforceUsername ]
          sfToken:
            !Sub
            - '{{resolve:secretsmanager:${SalesforceStage}/Salesforce/User/${SalesforceUsername}:SecretString:sfToken::${SalesforceUserSecretsVersion}}}'
            - SalesforceStage: !FindInMap [ StageMap, !Ref Stage, SalesforceStage ]
              SalesforceUserSecretsVersion: !FindInMap [ StageMap, !Ref Stage, SalesforceUserSecretsVersion ]
              SalesforceUsername: !FindInMap [ StageMap, !Ref Stage, SalesforceUsername ]
          sfUsername:
            !Sub
            - '{{resolve:secretsmanager:${SalesforceStage}/Salesforce/User/${SalesforceUsername}:SecretString:sfUsername::${SalesforceUserSecretsVersion}}}'
            - SalesforceStage: !FindInMap [ StageMap, !Ref Stage, SalesforceStage ]
              SalesforceUserSecretsVersion: !FindInMap [ StageMap, !Ref Stage, SalesforceUserSecretsVersion ]
              SalesforceUsername: !FindInMap [ StageMap, !Ref Stage, SalesforceUsername ]
          identityUrl:
            !Sub
            - '{{resolve:secretsmanager:${IdentityStage}/Identity/SoftOptInConsentAPI:SecretString:identityUrl::${IdentityUserSecretsVersion}}}'
            - IdentityStage: !FindInMap [ StageMap, !Ref Stage, IdentityStage ]
              IdentityUserSecretsVersion: !FindInMap [ StageMap, !Ref Stage, IdentityUserSecretsVersion ]
          identityToken:
            !Sub
            - '{{resolve:secretsmanager:${IdentityStage}/Identity/SoftOptInConsentAPI:SecretString:identityToken::${IdentityUserSecretsVersion}}}'
            - IdentityStage: !FindInMap [ StageMap, !Ref Stage, IdentityStage ]
              IdentityUserSecretsVersion: !FindInMap [ StageMap, !Ref Stage, IdentityUserSecretsVersion ]
      Events:
        ScheduledRun:
          Type: Schedule
          Properties:
            Schedule: !FindInMap [ StageMap, !Ref Stage, Schedule]
            Description: Runs Soft Opt-In Consent Setter
            Enabled: True
      Policies:
        - Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource:
                - !Sub arn:aws:s3:::soft-opt-in-consent-setter/${Stage}/ConsentsByProductMapping.json
        - Statement:
            - Effect: Allow
              Action: cloudwatch:PutMetricData
              Resource: "*"
        - Statement:
            - Sid: readDeployedArtefact
              Effect: Allow
              Action: s3:GetObject
              Resource:
                - arn:aws:s3::*:membership-dist/*

  failedRunAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    DependsOn:
      - LambdaFunction
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:retention-dev
      AlarmName: !Sub soft-opt-in-consent-setter-${Stage} failed to run
      AlarmDescription: >
        Two or more runs found an error and were unable to complete.
        See https://github.com/guardian/support-service-lambdas/blob/main/handlers/soft-opt-in-consent-setter/README.md#failedRunAlarm
        for possible causes, impacts and fixes.
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 3600
      Statistic: Sum
      Threshold: 2
      TreatMissingData: notBreaching

  failedUpdateAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    DependsOn:
      - LambdaFunction
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:retention-dev
      AlarmName: !Sub soft-opt-in-consent-setter-${Stage} failed to update Salesforce records
      AlarmDescription: >
        A run failed to update (some) records in Salesforce in the last hour.
        See https://github.com/guardian/support-service-lambdas/blob/main/handlers/soft-opt-in-consent-setter/README.md#failedUpdateAlarm
        for possible causes, impacts and fixes.
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: Stage
          Value: !Sub ${Stage}
      EvaluationPeriods: 1
      MetricName: failed_salesforce_update
      Namespace: soft-opt-in-consent-setter
      Period: 3600
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
