stacks:
  - membership
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  soft-opt-in-consent-setter-cloudformation:
    type: cloud-formation
    app: soft-opt-in-consent-setter
    parameters:
      templateStagePaths:
        CODE: soft-opt-in-consent-setter-CODE.template.json
        PROD: soft-opt-in-consent-setter-PROD.template.json

  soft-opt-in-consent-setter:
    type: aws-lambda
    parameters:
      fileName: soft-opt-in-consent-setter.jar
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
        - soft-opt-in-consent-setter-
        - soft-opt-in-consent-setter-IAP-
    dependencies: [soft-opt-in-consent-setter-cloudformation]