#!/bin/bash -e
# Generates _generated_tsIndex.ts inside each subdir and _generated_dirIndex.ts at the top level.
script_name=$(basename "$0")

script_dir=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")
data_dir=$(readlink -f "$script_dir/../../data")
repo_root=$(readlink -f "$script_dir/../../..")

file_header() {
    echo "/*"
    echo " * This file is gitignored and edits will be overwritten."
    echo " * Generated by $script_name"
    echo " * Generated on $(date)"
    echo " */"
}

# Convert a relative path to a safe TS identifier (replace non-alphanumeric with _), strip trailing .ts
to_safe_ts_identifier() {
    local importRel="$1"
    local without_ext="${importRel%.ts}"
    echo "$without_ext" | sed 's/[^a-zA-Z0-9]/_/g'
}

get_kind() {
    if [[ "$1" == *.inserts.ts ]]; then echo "insertion"; else echo "file"; fi
}


# Write _generated_tsIndex.ts for a single subdir.
# Scans subdir/templates/, imports each .ts file, exports a typed array.
write_ts_index() {
    local subdir="$1"
    local out="$subdir/_generated_tsIndex.ts"

    local imports=()
    local entries=()

    while IFS= read -r -d '' file; do
        local importRel="${file#$subdir/}"
        local import_path="${importRel%.ts}"
        local templateRel="${importRel#templates/}"
        local import_name kind
        import_name=$(to_safe_ts_identifier "$templateRel")
        kind=$(get_kind "$templateRel")
        imports+=("import $import_name from './$import_path';")
        entries+=("    {")
        entries+=("      relativeName: '$templateRel',")
        entries+=("      value: $import_name,")
        entries+=("      kind: '$kind',")
        entries+=("    },")
    done < <(find "$subdir/templates" -name "*.ts" -type f -print0 2>/dev/null | sort -fz)

    {
        echo "import type { TemplateEntry } from '../types';"
        for line in "${imports[@]}"; do echo "$line"; done
        echo "import type { TemplateParams } from './index';"
        echo ""
        file_header
        echo ""
        echo "export default {"
        echo "  templates: ["
        for line in "${entries[@]}"; do echo "$line"; done
        echo "  ] satisfies Array<TemplateEntry<TemplateParams>>,"
        echo "  templateDir: '${subdir#$repo_root/}/templates',"
        echo "}"
    } > "$out"

    echo "$script_name: wrote $out"
}


# Write _generated_dirIndex.ts at the top level of a data dir.
# Each entry is per-entry satisfies DirConfig<SeedTemplateParams>.
write_dir_index() {
    local parent_dir="$1"
    local out="$parent_dir/_generated_dirIndex.ts"

    local subdirs=()
    while IFS= read -r -d '' subdir; do
        subdirs+=("$(basename "$subdir")")
    done < <(find "$parent_dir" -mindepth 1 -maxdepth 1 -type d -not -name '_*' -print0 | sort -z)

    {
        for name in "${subdirs[@]}"; do
            local const_name
            const_name=$(to_safe_ts_identifier "$name")
            echo "import ${const_name}_templates from './$name/_generated_tsIndex';"
            echo "import ${const_name}_index from './$name/index';"
            echo "import type { TemplateParams as ${const_name}_TemplateParams } from './$name/index';"
        done
        echo "import type { DirConfig } from './types';"
        echo ""
        file_header
        echo ""
        echo "export default {"
        for name in "${subdirs[@]}"; do
            local const_name
            const_name=$(to_safe_ts_identifier "$name")
            echo "  '$name': {"
            echo "    index: ${const_name}_index,"
            echo "    templates: ${const_name}_templates,"
            echo "  } satisfies DirConfig<${const_name}_TemplateParams>,"
        done
        echo "};"
    } > "$out"

    echo "$script_name: wrote $out"
}


echo "$script_name: START generating template lists..."

# generate TS file indexes for both dirs
for parent_dir in "$data_dir/seeds" "$data_dir/managed"; do
    while IFS= read -r -d '' subdir; do
        [[ "$(basename "$subdir")" == _* ]] && continue
        write_ts_index "$subdir"
    done < <(find "$parent_dir" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)
done

# seeds index only needed for seeds
write_dir_index "$data_dir/seeds"

echo "$script_name: FINISH"
