#!/bin/bash -e
# This is an internally used script to automatically produce an index of managed templates
script_name=$(basename "$0")

script_dir=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")
data_dir=$(readlink -f "$script_dir/../../data")
repo_root=$(readlink -f "$script_dir/../../..")
managed_dir="$data_dir/managed"

file_header() {
    echo "/*"
    echo " * This file is gitignored and edits will be overwritten."
    echo " * Generated by $script_name"
    echo " * Generated on $(date)"
    echo " */"
}

# Convert a relative path to a safe TS identifier (replace non-alphanumeric with _), strip trailing .ts
to_safe_ts_identifier() {
    local importRel="$1"
    local without_ext="${importRel%.ts}"
    echo "$without_ext" | sed 's/[^a-zA-Z0-9]/_/g'
}


# Write _generated_tsIndex.ts for a single subdir.
# Scans subdir/templates/, imports each .ts file, exports a typed array.
write_ts_index() {
    local subdir="$1"
    local out="$subdir/_generated_tsIndex.ts"

    local imports=()
    local entries=()

    while IFS= read -r -d '' file; do
        local importRel="${file#$subdir/}"
        local import_path="${importRel%.ts}"
        local templateRel="${importRel#templates/}"
        local import_name
        import_name=$(to_safe_ts_identifier "$templateRel")
        imports+=("import $import_name from './$import_path';")
        entries+=("    { relativeName: '$templateRel', value: $import_name },")
    done < <(find "$subdir/templates" -name "*.ts" -type f -print0 2>/dev/null | sort -fz)

    {
        echo "import type { TemplateEntry } from '../types';"
        for line in "${imports[@]}"; do echo "$line"; done
        echo "import type { TemplateParams } from './index';"
        echo ""
        file_header
        echo ""
        echo "export default {"
        echo "  templates: ["
        for line in "${entries[@]}"; do echo "$line"; done
        echo "  ] satisfies Array<TemplateEntry<TemplateParams>>,"
        echo "  templateDir: '${subdir#$repo_root/}/templates',"
        echo "}"
    } > "$out"

    echo "$script_name: wrote $out"
}


echo "$script_name: START generating template lists..."

# generate TS file indexes for managed/*/
while IFS= read -r -d '' subdir; do
    [[ "$(basename "$subdir")" == _* ]] && continue
    write_ts_index "$subdir"
done < <(find "$managed_dir" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

echo "$script_name: FINISH"
