#!/bin/bash -e
# This script reads the pnpm catalog and makes it usable with auto complete in the build checker
script_name=$(basename "$0")

echo "$script_name: START generating deps list..."

script_dir=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")
buildcheck_dir=$(readlink -f "$script_dir/../..")
repo_root=$(readlink -f "$buildcheck_dir/..")
src_dir="$buildcheck_dir/src"
generated_dir="$src_dir/dynamic/generated"
workspace_file="$repo_root/pnpm-workspace.yaml"
output_file="$generated_dir/generatedDepsList.ts"

mkdir $generated_dir

catalog_section=$(awk -f "$(dirname "$0")/extractCatalog.awk" "$workspace_file")

echo "// This file is generated from the pnpm-workspace.yaml catalog and edits will be overwritten." > "$output_file"
echo "// Generated by $script_name on $(date)" >> "$output_file"
echo "" >> "$output_file"
echo "export const rawCatalogList = {" >> "$output_file"

echo "$catalog_section" | while IFS= read -r line; do
    [[ -z "$line" ]] && echo "" >> "$output_file" && continue
    [[ "$line" =~ ^# ]] && echo "  //${line:1}" >> "$output_file" && continue
    key=$(echo "$line" | awk -F: '{print $1}' | xargs)
    value=$(echo "$line" | awk -F: '{print $2}' | xargs)
    echo "  \"$key\": \"$value\"," >> "$output_file"
done

echo "} as const;" >> "$output_file"

echo "$script_name: FINISH wrote deps to $output_file"
