#!/bin/bash -e
# This is an internally used script to automatically produce an index of templates
script_name=$(basename "$0")

echo "$script_name: START generating template list..."

script_dir=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")
buildcheck_dir=$(readlink -f "$script_dir/../..")
repo_root=$(readlink -f "$buildcheck_dir/..")
echo "buildcheck_dir: $buildcheck_dir"
src_dir="$buildcheck_dir/src"
data_dir="$buildcheck_dir/data"
template_dir="$data_dir/templates"
seeds_dir="$data_dir/seeds"
generated_dir="$src_dir/dynamic/generated"
output_file="$generated_dir/generatedMappings.ts"

[[ -d "$generated_dir" ]] || mkdir $generated_dir

# Emit import lines for all *.ts files found under a directory.
# Usage: emit_imports <search_dir> <path_prefix_to_strip> <import_path_prefix>
emit_imports() {
    local search_dir="$1" strip_prefix="$2" import_prefix="$3"
    while IFS= read -r -d '' file; do
        local rel_path="${file#$strip_prefix/}"
        local name_without_ext="${rel_path%.ts}"
        local import_name
        import_name=$(echo "$name_without_ext" | sed 's/[^a-zA-Z0-9]/_/g')
        echo "import $import_name from '$import_prefix/$name_without_ext';"
    done < <(find "$search_dir" -name "*.ts" -type f -print0 2>/dev/null | sort -z) >> "$output_file"
}

# Emit a Template array const for all *.ts files found under a directory.
# Usage: emit_group <search_dir> <path_strip_prefix> <const_name> <type_expr>
emit_group() {
    local search_dir="$1" strip_prefix="$2" const_name="$3" type_expr="$4"
    echo "" >> "$output_file"
    echo "export const ${const_name}Templates: Array<Template<${type_expr}>> = [" >> "$output_file"
    while IFS= read -r -d '' file; do
        local from_repo_root="${file#$repo_root/}"
        local rel_path="${file#$strip_prefix/}"
        local name_without_ext="${rel_path%.ts}"
        local import_name template_name
        import_name=$(echo "$name_without_ext" | sed 's/[^a-zA-Z0-9]/_/g')
        template_name="${name_without_ext#*/}"  # strip first path segment (group name)
        echo "  { targetPath: \"$template_name\", value: $import_name, templateFilename: \"$from_repo_root\" },"
    done < <(find "$search_dir" -name "*.ts" -type f -print0 2>/dev/null | sort -z) >> "$output_file"
    echo "];" >> "$output_file"
}

# Discover managed subdirs
managed_subdirs=()
while IFS= read -r -d '' subdir; do
    managed_subdirs+=("$(basename "$subdir")")
done < <(find "$template_dir" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

# Discover seed names from *.ts files directly under seeds/ (e.g. new-api-lambda.ts -> new-api-lambda)
seed_names=()
while IFS= read -r -d '' file; do
    seed_names+=("$(basename "${file%.ts}")")
done < <(find "$seeds_dir" -mindepth 1 -maxdepth 1 -name "*.ts" -type f -print0 2>/dev/null | sort -z)

echo -n "" > "$output_file" # empty the file

echo "/* eslint-disable import/order -- import order is managed by the generator script */" >> "$output_file"
# Type imports first
echo "import type { HandlerDefinition, ModuleDefinition } from '../../../data/build';" >> "$output_file"
for seed_name in "${seed_names[@]}"; do
    const_name=$(echo "${seed_name}" | sed 's/[^a-zA-Z0-9]/_/g')
    echo "import type { GenerationOptions as ${const_name}_GenerationOptions } from '../../../data/seeds/${seed_name}';"
done >> "$output_file"

# Value imports: managed templates
for subdir_name in "${managed_subdirs[@]}"; do
    emit_imports "$template_dir/$subdir_name" "$template_dir" '../../../data/templates'
done

# Value imports: seed templates
for seed_name in "${seed_names[@]}"; do
    emit_imports "$seeds_dir/$seed_name" "$seeds_dir" '../../../data/seeds'
done

echo "import { type Template } from '../templater';" >> "$output_file"

echo "" >> "$output_file"
echo "/*" >> "$output_file"
echo " * This file is gitignored and edits will be overwritten." >> "$output_file"
echo " * Generated by $0" >> "$output_file"
echo " * Generated on $(date)" >> "$output_file"
echo " */" >> "$output_file"

# Managed template arrays
for subdir_name in "${managed_subdirs[@]}"; do
    const_name=$(echo "${subdir_name}" | sed 's/[^a-zA-Z0-9]/_/g')
    capitalized_const_name=$(echo "${const_name}" | awk '{print toupper(substr($0,0,1)) substr($0,2)}')
    emit_group "$template_dir/$subdir_name" "$template_dir" "$const_name" "${capitalized_const_name}Definition"
done

# Seed template arrays
for seed_name in "${seed_names[@]}"; do
    const_name=$(echo "${seed_name}" | sed 's/[^a-zA-Z0-9]/_/g')
    emit_group "$seeds_dir/$seed_name" "$seeds_dir" "$const_name" "${const_name}_GenerationOptions"
done

# Seed lookup object — individual arrays are precisely typed above; this lookup uses object as the common bound
echo "" >> "$output_file"
echo "export const seedTemplates: Record<string, Array<Template<never>>> = {" >> "$output_file"
for seed_name in "${seed_names[@]}"; do
    const_name=$(echo "${seed_name}" | sed 's/[^a-zA-Z0-9]/_/g')
    echo "  // eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- individual arrays are precisely typed; this lookup uses never as the common bound"
    echo "  '${seed_name}': ${const_name}Templates as unknown as Array<Template<never>>,"
done >> "$output_file"
echo "};" >> "$output_file"

echo "$script_name: FINISH generated $output_file"
