stacks:
  - membership
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  delivery-problem-credit-processor-cloudformation:
    type: cloud-formation
    app: delivery-problem-credit-processor
    parameters:
      templateStagePaths:
        CODE: delivery-problem-credit-processor-CODE.template.json
        PROD: delivery-problem-credit-processor-PROD.template.json
  delivery-problem-credit-processor:
    type: aws-lambda
    parameters:
      fileName: delivery-problem-credit-processor.jar
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
        - delivery-problem-credit-processor-
    dependencies: [delivery-problem-credit-processor-cloudformation]
