AWSTemplateFormatVersion: "2010-09-09"
Description: Zuora reporter

Parameters:
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - CODE
            - PROD
        Default: CODE

Mappings:
    StageVariables:
        CODE:
            ReadableS3Buckets:
              - arn:aws:s3:::gu-reader-revenue-private/membership/payment-failure-lambdas/DEV/*
              - arn:aws:s3:::gu-reader-revenue-private/membership/payment-failure-lambdas/CODE/*
        PROD:
            ReadableS3Buckets:
              - arn:aws:s3:::gu-reader-revenue-private/membership/payment-failure-lambdas/DEV/*
              - arn:aws:s3:::gu-reader-revenue-private/membership/payment-failure-lambdas/CODE/*
              - arn:aws:s3:::gu-reader-revenue-private/membership/payment-failure-lambdas/PROD/*

Conditions:
    CreateProdOnlyResources: !Equals [ !Ref Stage, PROD ]

Resources:
    ZuoraReportsRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                             - lambda.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /
            Policies:
                - PolicyName: LambdaPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                            - logs:CreateLogGroup
                            - logs:CreateLogStream
                            - logs:PutLogEvents
                            - lambda:InvokeFunction
                            Resource:
                            - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:`/aws/lambda/zuora-reports-${Stage}:log-stream:*

                - PolicyName: ReadPrivateCredentials
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action: s3:GetObject
                            Resource: !Sub arn:aws:s3:::gu-reader-revenue-private/membership/payment-failure-lambdas/${Stage}

    ZuoraReports:
        Type: AWS::Lambda::Function
        Properties:
            Description: no description yet
            FunctionName:
                !Sub zuora-reports-${Stage}
            Code:
                S3Bucket: membership-dist
                S3Key: !Sub membership/${Stage}/zuora-reports/zuora-reports.jar
            Handler: com.gu.zuora.reports.Handlers::queryHandler
            Environment:
                Variables:
                  Stage: !Ref Stage
            Role:
                !GetAtt ZuoraReportsRole.Arn
            MemorySize: 1536
            Runtime: java8
            Timeout: 300
        DependsOn:
        - ZuoraReportsRole
