stacks:
- membership
regions:
- eu-west-1
deployments:

  cfn:
    type: cloud-formation
    app: zuora-reports
    parameters:
      templatePath: cfn.yaml

  zuora-retention:
    type: aws-lambda
    parameters:
      fileName: zuora-reports.jar
      bucket: subscriptions-dist
      prefixStack: false
      functionNames:
      - zuora-reports-
    dependencies: [cfn]