stacks:
  - support
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  salesforce-disaster-recovery-health-check-cloudformation:
    type: cloud-formation
    app: salesforce-disaster-recovery-health-check
    parameters:
      templateStagePaths:
        CODE: salesforce-disaster-recovery-health-check-CODE.template.json
        PROD: salesforce-disaster-recovery-health-check-PROD.template.json

  salesforce-disaster-recovery-health-check:
    type: aws-lambda
    parameters:
      fileName: salesforce-disaster-recovery-health-check.zip
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
        - salesforce-disaster-recovery-health-check-
    dependencies: [salesforce-disaster-recovery-health-check-cloudformation]
