stacks:
- membership
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  cfn:
    type: cloud-formation
    app: sf-gocardless-sync
    parameters:
      templatePath: cfn.yaml


  sf-gocardless-sync:
    type: aws-lambda
    parameters:
      fileName: sf-gocardless-sync.jar
      bucket: support-service-lambdas-dist
      prefixStack: false
      functionNames:
      - sf-gocardless-sync-
    dependencies: [cfn]
