AWSTemplateFormatVersion: "2010-09-09"
Description: HTTP API to push a metric to cloudwatch so we can alarm on errors

Parameters:
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - PROD
            - CODE

Mappings:
    StageMap:
        CODE:
            ApiName: metric-push-api-api-CODE
            DomainName: metric-push-api-code.support.guardianapis.com
            AlarmActionsEnabled: FALSE
        PROD:
            ApiName: metric-push-api-api-PROD
            DomainName: metric-push-api-prod.support.guardianapis.com
            AlarmActionsEnabled: TRUE
    Constants:
      Alarm:
        Process: Follow the process in https://docs.google.com/document/d/1_3El3cly9d7u_jPgTcRjLxmdG2e919zCLvmcFCLOYAk/edit
        Urgent: URGENT 9-5 -

Resources:

    MetricPushProxyResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref MetricPushAPI
            ParentId: !GetAtt [MetricPushAPI, RootResourceId]
            PathPart: metric-push-api
        DependsOn: MetricPushAPI

    MetricPushMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            ApiKeyRequired: false
            RestApiId: !Ref MetricPushAPI
            ResourceId: !Ref MetricPushProxyResource
            HttpMethod: GET
            Integration:
              Type: MOCK
              RequestTemplates:
                application/json: '{"statusCode": 200}'
              IntegrationResponses:
                - StatusCode: 204
                  ResponseParameters:
                    method.response.header.Cache-control: '''no-cache'''
            MethodResponses:
              - StatusCode: 204
                ResponseParameters:
                  method.response.header.Cache-control: true
        DependsOn:
        - MetricPushAPI
        - MetricPushProxyResource

    MetricPushAPI:
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            Description: HTTP API to push a metric to cloudwatch so we can alarm on errors
            Name: !FindInMap [StageMap, !Ref Stage, ApiName]

    MetricPushAPIStage:
        Type: AWS::ApiGateway::Stage
        Properties:
            Description: Stage for metric-push-api
            RestApiId: !Ref MetricPushAPI
            DeploymentId: !Ref MetricPushAPIDeployment
            StageName: !Sub ${Stage}
            MethodSettings:
            - ResourcePath: '/*'
              HttpMethod: '*'
              LoggingLevel: ERROR
              DataTraceEnabled: true
        DependsOn: MetricPushMethod

    MetricPushAPIDeployment:
        Type: AWS::ApiGateway::Deployment
        Properties:
            Description: Deploys metric-push-api into an environment/stage
            RestApiId: !Ref MetricPushAPI
        DependsOn: MetricPushMethod

    MetricPushDomainName:
      Type: "AWS::ApiGateway::DomainName"
      Properties:
        RegionalCertificateArn: # only for *.support.guardianapis.com
          !Sub arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/b384a6a0-2f54-4874-b99b-96eeff96c009
        DomainName: !FindInMap [ StageMap, !Ref Stage, DomainName ]
        EndpointConfiguration:
          Types:
            - REGIONAL

    MetricPushBasePathMapping:
      Type: "AWS::ApiGateway::BasePathMapping"
      Properties:
        RestApiId: !Ref MetricPushAPI
        DomainName: !Ref MetricPushDomainName
        Stage: !Sub ${Stage}
      DependsOn:
      - MetricPushAPI
      - MetricPushAPIStage
      - MetricPushDomainName

    MetricPushDNSRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: support.guardianapis.com.
        Name: !FindInMap [ StageMap, !Ref Stage, DomainName ]
        Comment: !Sub CNAME for metric-push-api API ${Stage}
        Type: CNAME
        TTL: '120'
        ResourceRecords:
        - !GetAtt [ MetricPushDomainName, RegionalDomainName ]
      DependsOn:
        - MetricPushDomainName

    5xxApiAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmActions:
          - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alarms-handler-topic-${Stage}
        ActionsEnabled: !FindInMap [StageMap, !Ref Stage, AlarmActionsEnabled]
        AlarmName: !Join
        - ' '
        - - !FindInMap [ Constants, Alarm, Urgent ]
          - !Ref 'Stage'
          - !FindInMap [StageMap, !Ref Stage, ApiName]
          - 'API Gateway is returning 5XX errors'
        ComparisonOperator: GreaterThanThreshold
        Dimensions:
          - Name: ApiName
            Value: !FindInMap [StageMap, !Ref Stage, ApiName]
          - Name: Stage
            Value: !Sub ${Stage}
        EvaluationPeriods: 1
        MetricName: 5XXError
        Namespace: AWS/ApiGateway
        Period: 60
        Statistic: Sum
        Threshold: 2
        TreatMissingData: notBreaching

    HighClientSideErrorRateAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmActions:
          - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alarms-handler-topic-${Stage}
        ActionsEnabled: !FindInMap [StageMap, !Ref Stage, AlarmActionsEnabled]
        AlarmName: !Join
          - ' '
          - - !FindInMap [ Constants, Alarm, Urgent ]
            - !Ref 'Stage'
            - 'client-side fatal errors are being reported to sentry for support-frontend'
        AlarmDescription: !Join
          - ' '
          - - 'Impact - some or all browsers are failing to render support client side pages. Log in to Sentry to see these errors: https://the-guardian.sentry.io/discover/results/?project=1213654&query=%22Fatal%20error%20rendering%20page%22&queryDataset=error-events&sort=-count&statsPeriod=24h'
            - !FindInMap [ Constants, Alarm, Process ]
            - !FindInMap [StageMap, !Ref Stage, ApiName]
        Metrics:
          - Id: mtotal2xx
            Expression: 'mtotalcount - (m5xxcount + m4xxcount)'
          - Id: mtotalcount
            ReturnData: false
            MetricStat:
              Period: 60
              Stat: Sum
              Metric:
                Namespace: AWS/ApiGateway
                MetricName: Count
                Dimensions:
                  - Name: ApiName
                    Value: !FindInMap [StageMap, !Ref Stage, ApiName]
          - Id: m5xxcount
            ReturnData: false
            MetricStat:
              Period: 60
              Stat: Sum
              Metric:
                Namespace: AWS/ApiGateway
                MetricName: 5XXError
                Dimensions:
                  - Name: ApiName
                    Value: !FindInMap [StageMap, !Ref Stage, ApiName]
          - Id: m4xxcount
            ReturnData: false
            MetricStat:
              Period: 60
              Stat: Sum
              Metric:
                Namespace: AWS/ApiGateway
                MetricName: 5XXError
                Dimensions:
                  - Name: ApiName
                    Value: !FindInMap [StageMap, !Ref Stage, ApiName]
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Threshold: 2
        DatapointsToAlarm: 3
        EvaluationPeriods: 5
        TreatMissingData: notBreaching
      DependsOn:
        - MetricPushAPI
