stacks:
  - membership
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  metric-push-api-cloudformation:
    type: cloud-formation
    app: metric-push-api
    parameters:
      templateStagePaths:
        CODE: metric-push-api-CODE.template.json
        PROD: metric-push-api-PROD.template.json
