stacks:
- membership
regions:
- eu-west-1
deployments:

  cfn:
    type: cloud-formation
    app: digital-voucher-cancellation-processor
    parameters:
      templatePath: cdk-cfn.yaml

  digital-voucher-cancellation-processor:
    type: aws-lambda
    parameters:
      fileName: digital-voucher-cancellation-processor.jar
      bucket: support-service-lambdas-dist
      prefixStack: false
      functionNames:
      - digital-voucher-cancellation-processor-
    dependencies: [cfn]
