stacks:
  - support
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  discount-expiry-notifier-cloudformation:
    type: cloud-formation
    app: discount-expiry-notifier
    parameters:
      templateStagePaths:
        CODE: discount-expiry-notifier-CODE.template.json
        PROD: discount-expiry-notifier-PROD.template.json
  discount-expiry-notifier:
    type: aws-lambda
    parameters:
      fileName: discount-expiry-notifier.zip
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
        - discount-expiry-notifier-get-subs-with-expiring-discounts-
        - discount-expiry-notifier-build-email-payload-
    dependencies: [discount-expiry-notifier-cloudformation]
