stacks:
- membership
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  cfn:
    type: cloud-formation
    app: zuora-datalake-export
    parameters:
      templatePath: cfn.yaml
  zuora-datalake-export:
    type: aws-lambda
    parameters:
      fileName: zuora-datalake-export.jar
      bucket: support-service-lambdas-dist
      prefixStack: false
      functionNames:
      - zuora-datalake-export-
    dependencies: [cfn]