AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Endpoints to handle stripe webhooks

Parameters:
  App:
    Description: Endpoints to handle stripe webhooks
    Type: String
    Default: stripe-webhook-endpoints
  Stack:
    Description: Stack name
    Type: String
    Default: membership
  Stage:
    Description: Set by RiffRaff on each deploy
    Type: String
    AllowedValues:
      - CODE
      - PROD
  DeployBucket:
    Description: Bucket to copy files to
    Type: String
    Default: membership-dist

Conditions:
  IsProd: !Equals [ !Ref Stage, "PROD" ]

Resources:
  PaymentIntentIssuesLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub stripe-payment-intent-issues-${Stage}
      Description: A lambda for handling payment intent issues (cancellation, failure, action required)
      Runtime: java11
      Handler: com.gu.paymentIntentIssues.Lambda::handler
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          App: payment-intent-issues
          Stack: !Ref Stack
          Stage: !Ref Stage
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/${App}/${App}.jar
      Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          Effect: Allow
          Action:
            - ssm:GetParametersByPath
          Resource:
            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/membership/payment-intent-issues
      - Statement:
        - Effect: Allow
          Action: s3:GetObject
          Resource:
            - arn:aws:s3::*:membership-dist/*
      Events:
        AcquisitionEvent:
            Type: Api
            Properties:
                Path: '/payment-intent-issue'
                Method: post
  CustomerUpdatedLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub stripe-customer-updated-${Stage}
      Description: A lambda for handling customer updates
      Runtime: java11
      Handler: com.gu.stripeCardUpdated.Lambda::apply
      MemorySize: 1356
      Timeout: 900
      Environment:
        Variables:
          App: stripe-customer-updated
          Stack: !Ref Stack
          Stage: !Ref Stage
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/${App}/${App}.jar
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - ssm:GetParametersByPath
            Resource:
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/membership/payment-intent-issues
        - Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource:
                - arn:aws:s3::*:membership-dist/*
                - !Sub arn:aws:s3:::gu-reader-revenue-private/membership/support-service-lambdas/${Stage}/zuoraRest-${Stage}.*.json
                - !Sub arn:aws:s3:::gu-reader-revenue-private/membership/support-service-lambdas/${Stage}/trustedApi-${Stage}.*.json
                - !Sub arn:aws:s3:::gu-reader-revenue-private/membership/support-service-lambdas/${Stage}/stripe-${Stage}.*.json
      Events:
        AcquisitionEvent:
          Type: Api
          Properties:
            Path: '/customer-updated'
            Method: post
            RequestParameters:
              - method.request.querystring.apiToken
