stacks:
- membership
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  stripe-webhook-endpoints:
    type: aws-lambda
    parameters:
      bucket: membership-dist
      functionNames:
      - stripe-payment-intent-issues-
      - stripe-customer-updated-
      fileName: stripe-webhook-endpoints.jar
      prefixStack: false
    dependencies: [ cfn ]
  cfn:
    type: cloud-formation
    app: stripe-webhook-endpoints
    parameters:
      templatePath: cfn.yaml
