stacks:
  - membership
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  stripe-webhook-endpoints-cloudformation:
    type: cloud-formation
    app: stripe-webhook-endpoints
    parameters:
      templateStagePaths:
        CODE: stripe-webhook-endpoints-CODE.template.json
        PROD: stripe-webhook-endpoints-PROD.template.json

  stripe-webhook-endpoints:
    type: aws-lambda
    parameters:
      fileName: stripe-webhook-endpoints.jar
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
        - stripe-payment-intent-issues-
        - stripe-customer-updated-
    dependencies: [stripe-webhook-endpoints-cloudformation]
