stacks:
- support
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  stripe-disputes-cloudformation:
    type: cloud-formation
    app: stripe-disputes
    parameters:
      templateStagePaths:
        CODE: stripe-disputes-CODE.template.json
        PROD: stripe-disputes-PROD.template.json

  stripe-disputes:
    type: aws-lambda
    parameters:
      fileName: stripe-disputes.zip
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
      - stripe-disputes-
    dependencies: [stripe-disputes-cloudformation]
