AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda for distributing revenue on a regular basis

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
    Default: CODE

Mappings:
  Stages:
    Schedule:
      CODE: 'rate(365 days)'
      PROD: 'cron(0 3,15 2-31 * *)'
  Constants:
    Alarm:
      Process: See the docs at https://github.com/guardian/support-service-lambdas/tree/main/handlers/revenue-recogniser-job

Conditions:
  ProdOnlyResource: !Equals [!Ref Stage, PROD]

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Recognises unrecognised revenue in Zuora
      FunctionName:
        !Sub revenue-recogniser-job-${Stage}
      Handler: com.gu.recogniser.Handler::handleRequest
      CodeUri:
        Bucket: support-service-lambdas-dist
        Key: !Sub membership/${Stage}/revenue-recogniser-job/revenue-recogniser-job.jar
      MemorySize: 2048
      Runtime: java11
      Timeout: 900
      Environment:
        Variables:
          Stage: !Ref Stage
      Events:
        RerunTests:
          Type: Schedule
          Properties:
            Schedule: !FindInMap [ Stages, Schedule, !Ref Stage ]
            Description: Recognises unrecognised revenue in Zuora
      EventInvokeConfig:
        MaximumRetryAttempts: 2
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - lambda:InvokeFunction
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/revenue-recogniser-job-${Stage}:log-stream:*"
        - Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource:
                - !Sub arn:aws:s3:::gu-reader-revenue-private/membership/support-service-lambdas/${Stage}/zuoraRest-${Stage}.*.json
        - Statement:
            - Effect: Allow
              Action: cloudwatch:PutMetricData
              Resource: "*"

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: LambdaFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/revenue-recogniser-job-${Stage}
      RetentionInDays: 90

  NotRunningAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: ProdOnlyResource
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:reader-revenue-dev
      AlarmName: !Join
        - ' '
        - - 'non urgent -'
          - 'revenue recogniser job is not running'
      AlarmDescription: !Join
        - ' '
        - - 'Impact - Accounts team will not see all revenue correctly for manually recognised subs'
          - !FindInMap [ Constants, Alarm, Process ]
      Metrics:
        - Id: total
          Expression: "FILL(m1,0)"
          Label: RunCount
        - Id: m1
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: support-service-lambdas
              MetricName: job-succeeded
              Dimensions:
                - Name: Stage
                  Value: !Ref Stage
                - Name: app
                  Value: revenue-recogniser-job
            Stat: Sum
            Period: 3600
            Unit: Count
      ComparisonOperator: LessThanThreshold
      Threshold: 1
      EvaluationPeriods: 24
      TreatMissingData: breaching

  FailedRecognitionAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: ProdOnlyResource
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:reader-revenue-dev
      AlarmName: !Join
        - ' '
        - - 'non urgent -'
          - 'revenue recogniser job could not process a record'
      AlarmDescription: !Join
        - ' '
        - - 'Impact - Accounts team will not see all revenue correctly for manually recognised subs'
          - !FindInMap [ Constants, Alarm, Process ]
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: Stage
          Value: !Ref Stage
      EvaluationPeriods: 1
      MetricName: could-not-recognise-revenue
      Namespace: support-service-lambdas
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
