stacks:
- membership
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  discount-api-cloudformation:
    type: cloud-formation
    app: discount-api
    parameters:
      templateStagePaths:
        CODE: discount-api-CODE.template.json
        PROD: discount-api-PROD.template.json

  discount-api:
    type: aws-lambda
    parameters:
      fileName: discount-api.jar
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
      - discount-api-
    dependencies: [discount-api-cloudformation]
