stacks:
- membership
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  cfn:
    type: cloud-formation
    app: digital-voucher-api
    parameters:
      templatePath: cfn.yaml

  discount-api:
    type: aws-lambda
    parameters:
      fileName: digital-voucher-api.jar
      bucket: support-service-lambdas-dist
      prefixStack: false
      functionNames:
      - digital-voucher-api-
    dependencies: [cfn]
