stacks:
- membership
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  cfn:
    type: cloud-formation
    app: identity-retention
    parameters:
      templatePath: cfn.yaml

  identity-retention:
    type: aws-lambda
    parameters:
      fileName: identity-retention.jar
      bucket: support-service-lambdas-dist
      prefixStack: false
      functionNames:
      - identity-retention-
    dependencies: [cfn]
