stacks:
- support
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  generate-product-catalog-cloudformation:
    type: cloud-formation
    app: generate-product-catalog
    parameters:
      templateStagePaths:
        CODE: generate-product-catalog-CODE.template.json
        PROD: generate-product-catalog-PROD.template.json

  generate-product-catalog:
    type: aws-lambda
    parameters:
      fileName: generate-product-catalog.zip
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
      - generate-product-catalog-
    dependencies: [generate-product-catalog-cloudformation]
