# MANAGED FILE: to push changes see buildcheck/README.md - template: buildcheck/data/managed/handler/templates/riff-raff.yaml.ts
stacks:
  - support
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  user-subscriptions-api-cloudformation:
    type: cloud-formation
    app: user-subscriptions-api
    parameters:
      templateStagePaths:
        CODE: user-subscriptions-api-CODE.template.json
        PROD: user-subscriptions-api-PROD.template.json
  user-subscriptions-api:
    type: aws-lambda
    parameters:
      fileName: user-subscriptions-api.zip
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
        - user-subscriptions-api-
    dependencies:
      - user-subscriptions-api-cloudformation
