stacks:
  - support
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  mparticle-api-cloudformation:
    type: cloud-formation
    app: mparticle-api
    parameters:
      templateStagePaths:
        CODE: mparticle-api-CODE.template.json
        PROD: mparticle-api-PROD.template.json

  mparticle-api:
    type: aws-lambda
    parameters:
      fileName: mparticle-api.zip
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
      - mparticle-api-
    dependencies: [mparticle-api-cloudformation]
