stacks:
  - membership
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  single-contributions-processor-cloudformation:
    type: cloud-formation
    app: single-contributions-processor
    parameters:
      templateStagePaths:
        CODE: single-contributions-processor-CODE.template.json
        PROD: single-contributions-processor-PROD.template.json
