Parameters:
  stage:
    Type: String
    Description: Stage
  officeIpRange:
    Type: String
    Description: officeIpRange
  salesForceIpRanges:
    Type: CommaDelimitedList
    Description: salesForceIpRanges
Resources:
  sfMoveSubscriptionsFnRole6D1AF23F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Tags:
        - Key: App
          Value: sf-move-subscriptions-api
        - Key: Stage
          Value:
            Ref: stage
        - Key: Stack
          Value: membership
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sfMoveSubscriptionsFnRole/Resource
  sfMoveSubscriptionsFnRoleDefaultPolicyBD9AFEB9:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: ssm:GetParametersByPath
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter/
                  - Ref: stage
                  - /membership/sf-move-subscriptions-api
          - Action: kms:Decrypt
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:kms:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :alias/aws/ssm
          - Action: logs:CreateLogGroup
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:logs:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :*
          - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:logs:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :log-group:/aws/lambda/sf-move-subscriptions-api-
                  - Ref: stage
                  - :*
        Version: "2012-10-17"
      PolicyName: sfMoveSubscriptionsFnRoleDefaultPolicyBD9AFEB9
      Roles:
        - Ref: sfMoveSubscriptionsFnRole6D1AF23F
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sfMoveSubscriptionsFnRole/DefaultPolicy/Resource
  sfMoveSubscriptionsLambdaFFEA4DBB:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: support-service-lambdas-dist
        S3Key:
          Fn::Join:
            - ""
            - - membership/
              - Ref: stage
              - /sf-move-subscriptions-api/sf-move-subscriptions-api.jar
      Handler: com.gu.sf.move.subscriptions.api.Handler::handle
      Role:
        Fn::GetAtt:
          - sfMoveSubscriptionsFnRole6D1AF23F
          - Arn
      Runtime: java8
      Environment:
        Variables:
          App: sf-move-subscriptions-api
          Stage:
            Ref: stage
          Stack: membership
      FunctionName:
        Fn::Join:
          - ""
          - - sf-move-subscriptions-api-
            - Ref: stage
      MemorySize: 1536
      Tags:
        - Key: App
          Value: sf-move-subscriptions-api
        - Key: Stage
          Value:
            Ref: stage
        - Key: Stack
          Value: membership
      Timeout: 300
    DependsOn:
      - sfMoveSubscriptionsFnRoleDefaultPolicyBD9AFEB9
      - sfMoveSubscriptionsFnRole6D1AF23F
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sfMoveSubscriptionsLambda/Resource
  sfmovesubscriptionsapi1E2B2153:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: HEADER
      Description:
        Fn::Join:
          - ""
          - - "API for for moving subscriptions in Salesforce in "
            - Ref: stage
            - " env"
      Name:
        Fn::Join:
          - ""
          - - sf-move-subscriptions-api-
            - Ref: stage
      Policy:
        Statement:
          - Action: execute-api:Invoke
            Effect: Allow
            Principal: "*"
            Resource: execute-api:/*/*/*
          - Action: execute-api:Invoke
            Condition:
              NotIpAddress:
                aws:SourceIp:
                  Fn::Split:
                    - ","
                    - Fn::Join:
                        - ""
                        - - Fn::Join:
                              - ","
                              - Ref: salesForceIpRanges
                          - ","
                          - Ref: officeIpRange
            Effect: Deny
            Principal: "*"
            Resource: execute-api:/*/*/*
        Version: "2012-10-17"
      Tags:
        - Key: App
          Value: sf-move-subscriptions-api
        - Key: Stage
          Value:
            Ref: stage
        - Key: Stack
          Value: membership
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sf-move-subscriptions-api/Resource
  sfmovesubscriptionsapiDeployment823989FDa9cd173c0ce8c01baea2dede41b4f2f8:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: sfmovesubscriptionsapi1E2B2153
      Description: Automatically created by the RestApi construct
    DependsOn:
      - sfmovesubscriptionsapiproxyANY8BB1BC8E
      - sfmovesubscriptionsapiproxy4CE36BC9
      - sfmovesubscriptionsapiANYC6788DCE
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sf-move-subscriptions-api/Deployment/Resource
  sfmovesubscriptionsapiDeploymentStageobjectObject0B1836AE:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: sfmovesubscriptionsapi1E2B2153
      DeploymentId:
        Ref: sfmovesubscriptionsapiDeployment823989FDa9cd173c0ce8c01baea2dede41b4f2f8
      StageName:
        Ref: stage
      Tags:
        - Key: App
          Value: sf-move-subscriptions-api
        - Key: Stage
          Value:
            Ref: stage
        - Key: Stack
          Value: membership
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sf-move-subscriptions-api/DeploymentStage.[object Object]/Resource
  sfmovesubscriptionsapiCloudWatchRoleEB8406DC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Tags:
        - Key: App
          Value: sf-move-subscriptions-api
        - Key: Stage
          Value:
            Ref: stage
        - Key: Stack
          Value: membership
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sf-move-subscriptions-api/CloudWatchRole/Resource
  sfmovesubscriptionsapiAccount21F56D5B:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - sfmovesubscriptionsapiCloudWatchRoleEB8406DC
          - Arn
    DependsOn:
      - sfmovesubscriptionsapi1E2B2153
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sf-move-subscriptions-api/Account
  sfmovesubscriptionsapiANYApiPermissionSfMoveSubscriptionsStacksfmovesubscriptionsapiE5FD007CANY5E82890D:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - sfMoveSubscriptionsLambdaFFEA4DBB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: sfmovesubscriptionsapi1E2B2153
            - /
            - Ref: sfmovesubscriptionsapiDeploymentStageobjectObject0B1836AE
            - /*/
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sf-move-subscriptions-api/Default/ANY/ApiPermission.SfMoveSubscriptionsStacksfmovesubscriptionsapiE5FD007C.ANY..
  sfmovesubscriptionsapiANYApiPermissionTestSfMoveSubscriptionsStacksfmovesubscriptionsapiE5FD007CANY4B02B073:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - sfMoveSubscriptionsLambdaFFEA4DBB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: sfmovesubscriptionsapi1E2B2153
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sf-move-subscriptions-api/Default/ANY/ApiPermission.Test.SfMoveSubscriptionsStacksfmovesubscriptionsapiE5FD007C.ANY..
  sfmovesubscriptionsapiANYC6788DCE:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - sfmovesubscriptionsapi1E2B2153
          - RootResourceId
      RestApiId:
        Ref: sfmovesubscriptionsapi1E2B2153
      ApiKeyRequired: true
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - sfMoveSubscriptionsLambdaFFEA4DBB
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sf-move-subscriptions-api/Default/ANY/Resource
  sfmovesubscriptionsapiproxy4CE36BC9:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - sfmovesubscriptionsapi1E2B2153
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: sfmovesubscriptionsapi1E2B2153
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sf-move-subscriptions-api/Default/{proxy+}/Resource
  sfmovesubscriptionsapiproxyANYApiPermissionSfMoveSubscriptionsStacksfmovesubscriptionsapiE5FD007CANYproxyC5A8F39F:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - sfMoveSubscriptionsLambdaFFEA4DBB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: sfmovesubscriptionsapi1E2B2153
            - /
            - Ref: sfmovesubscriptionsapiDeploymentStageobjectObject0B1836AE
            - /*/{proxy+}
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sf-move-subscriptions-api/Default/{proxy+}/ANY/ApiPermission.SfMoveSubscriptionsStacksfmovesubscriptionsapiE5FD007C.ANY..{proxy+}
  sfmovesubscriptionsapiproxyANYApiPermissionTestSfMoveSubscriptionsStacksfmovesubscriptionsapiE5FD007CANYproxy68A19293:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - sfMoveSubscriptionsLambdaFFEA4DBB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: sfmovesubscriptionsapi1E2B2153
            - /test-invoke-stage/*/{proxy+}
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sf-move-subscriptions-api/Default/{proxy+}/ANY/ApiPermission.Test.SfMoveSubscriptionsStacksfmovesubscriptionsapiE5FD007C.ANY..{proxy+}
  sfmovesubscriptionsapiproxyANY8BB1BC8E:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: sfmovesubscriptionsapiproxy4CE36BC9
      RestApiId:
        Ref: sfmovesubscriptionsapi1E2B2153
      ApiKeyRequired: true
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - sfMoveSubscriptionsLambdaFFEA4DBB
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sf-move-subscriptions-api/Default/{proxy+}/ANY/Resource
  sfMoveSubscriptionsApiKeyBDEEA81B:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Enabled: true
      Name:
        Fn::Join:
          - ""
          - - sf-move-subscriptions-api-key-
            - Ref: stage
      StageKeys:
        - RestApiId:
            Ref: sfmovesubscriptionsapi1E2B2153
          StageName:
            Ref: sfmovesubscriptionsapiDeploymentStageobjectObject0B1836AE
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sfMoveSubscriptionsApiKey/Resource
  sfMoveSubscriptionsApiUsagePlan6EC96D73:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId:
            Ref: sfmovesubscriptionsapi1E2B2153
          Stage:
            Ref: sfmovesubscriptionsapiDeploymentStageobjectObject0B1836AE
          Throttle: {}
      UsagePlanName:
        Fn::Join:
          - ""
          - - sf-move-subscriptions-api-usage-plan-
            - Ref: stage
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sfMoveSubscriptionsApiUsagePlan/Resource
  sfMoveSubscriptionsApiUsagePlanUsagePlanKeyResource6EAD919B:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId:
        Ref: sfMoveSubscriptionsApiKeyBDEEA81B
      KeyType: API_KEY
      UsagePlanId:
        Ref: sfMoveSubscriptionsApiUsagePlan6EC96D73
    Metadata:
      aws:cdk:path: SfMoveSubscriptionsStack/sfMoveSubscriptionsApiUsagePlan/UsagePlanKeyResource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.27.0,@aws-cdk/assets=1.27.0,@aws-cdk/aws-apigateway=1.27.0,@aws-cdk/aws-cloudwatch=1.27.0,@aws-cdk/aws-ec2=1.27.0,@aws-cdk/aws-events=1.27.0,@aws-cdk/aws-iam=1.27.0,@aws-cdk/aws-kms=1.27.0,@aws-cdk/aws-lambda=1.27.0,@aws-cdk/aws-logs=1.27.0,@aws-cdk/aws-s3=1.27.0,@aws-cdk/aws-s3-assets=1.27.0,@aws-cdk/aws-sqs=1.27.0,@aws-cdk/aws-ssm=1.27.0,@aws-cdk/core=1.27.0,@aws-cdk/cx-api=1.27.0,@aws-cdk/region-info=1.27.0,jsii-runtime=node.js/v13.6.0
    Condition: CDKMetadataAvailable
Outputs:
  sfmovesubscriptionsapiEndpoint4288D4E9:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: sfmovesubscriptionsapi1E2B2153
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: sfmovesubscriptionsapiDeploymentStageobjectObject0B1836AE
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

