#!/bin/bash -e
# This is an internally used script to automatically produce an index of templates
script_name=$(basename "$0")

echo "$script_name: START generating template list..."

script_dir=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")
buildgen_dir=$(readlink -f "$script_dir/..")
src_dir="$buildgen_dir/src"
data_dir="$buildgen_dir/data"
template_dir="$data_dir/handlerTemplate"
output_file="$src_dir/steps/generatedMappings.ts"

template_files=()
while IFS= read -r -d '' file; do
    rel_path="${file#$template_dir/}"
    name_without_ext="${rel_path%.ts}"
    template_files+=("$name_without_ext")
done < <(find "$template_dir" -name "*.ts" -type f -print0 | sort -z)

echo -n "" > "$output_file" # empty the file

# Generate imports
for name_without_ext in "${template_files[@]}"; do
    import_name=$(echo "$name_without_ext" | sed 's/[^a-zA-Z0-9]/_/g')
    echo "import $import_name from '../../data/handlerTemplate/$name_without_ext';"
done >> "$output_file"
echo "import { type Template } from '../util/templater';" >> "$output_file"

echo "" >> "$output_file"
echo "/*" >> "$output_file"
echo " * This file is gitignored and edits will be overwritten." >> "$output_file"
echo " * Generated by $0" >> "$output_file"
echo " * Generated on $(date)" >> "$output_file"
echo " */" >> "$output_file"
echo "" >> "$output_file"

echo "const templates: Template[] = [" >> "$output_file"

# Generate array entries
for name_without_ext in "${template_files[@]}"; do
    import_name=$(echo "$name_without_ext" | sed 's/[^a-zA-Z0-9]/_/g')
    echo "  { name: \"$name_without_ext\", template: $import_name },"
done >> "$output_file"

echo "];" >> "$output_file"
echo "" >> "$output_file"
echo "// eslint-disable-next-line import/no-default-export -- generated file" >> "$output_file"
echo "export default templates;" >> "$output_file"

echo "$script_name: FINISH wrote ${#template_files[@]} templates to $output_file"
