stacks:
- support
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  test-api-cloudformation:
    type: cloud-formation
    app: test-api
    parameters:
      templateStagePaths:
        CODE: test-api-CODE.template.json
        PROD: test-api-PROD.template.json

  test-api:
    type: aws-lambda
    parameters:
      fileName: test-api.zip
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
      - test-api-
    dependencies: [test-api-cloudformation]
