stacks:
- subscriptions
regions:
- eu-west-1
deployments:

  cfn:
    type: cloud-formation
    app: catalog-service
    parameters:
      templatePath: cfn.yaml
      cloudFormationStackName: catalog-service-
      prependStackToCloudFormationStackName: false

  catalog-service:
    type: aws-lambda
    parameters:
      fileName: catalog-service.jar
      bucket: subscriptions-dist
      prefixStack: false
      functionNames:
      - catalog-service-
    dependencies: [cfn]