stacks:
- subscriptions
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  cfn:
    type: cloud-formation
    app: catalog-service
    parameters:
      templatePath: cfn.yaml

  catalog-service:
    type: aws-lambda
    parameters:
      fileName: catalog-service.jar
      bucket: subscriptions-dist
      prefixStack: false
      functionNames:
      - catalog-service-zuora-code-
      - catalog-service-zuora-prod-
    dependencies: [cfn]