stacks:
- subscriptions
regions:
- eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  cfn:
    type: cloud-formation
    app:  digital-subscription-expiry
    parameters:
      templatePath: cfn.yaml

  digital-subscription-expiry:
    type: aws-lambda
    parameters:
      fileName: digital-subscription-expiry.jar
      bucket: subscriptions-dist
      prefixStack: false
      functionNames:
      - digital-subscription-expiry-
    dependencies: [cfn]
