import { relativePath } from './notices';
import path from 'path';
import { GeneratedFile } from '../../steps/generatedFile';

// the generated file is named after this file.
// if you rename it, clean the snapshot first, then generate afterwards
const basename = path.basename(__filename);
if (!basename.endsWith('.ts')) {
	throw new Error(
		`Expected warning file name to end with .ts, got: ${basename}`,
	);
}
export const warningFileName = basename.slice(0, -3);

export function generateWarningFile(
	generatedFiles: string[],
	pathToRoot: string,
): GeneratedFile {
	const buildGenHeader = `# Buildcheck managed file list
The files listed below are managed by buildcheck and their content is checked by the build.

## HOWTO edit managed files
1. edit the build definition in buildcheck/src/data/
2. run \`pnpm update-build\` at the root

For further details, see [buildcheck/README.md](${pathToRoot}/buildcheck/README.md)

## Generated file list:
`;

	const buildGenFooter =
		'\nThis file is generated by [' +
		relativePath(__filename) +
		'](' +
		pathToRoot +
		'/' +
		relativePath(__filename) +
		')\n';

	return {
		relativePath: warningFileName,
		content:
			buildGenHeader +
			[...generatedFiles, warningFileName]
				.map((name) => '- [' + name + '](' + name + ')\n')
				.join('') +
			buildGenFooter,
	};
}

export function parseGeneratedFilenames(fileLines: string[]): string[] {
	// lines to look for are like this: "- [filename](filepath)"
	return fileLines
		.filter((line) => line.startsWith('- ['))
		.map((line) => {
			const getTheContentsOfRoundBrackets = /\(([^)]+)\)/;
			const match = line.match(getTheContentsOfRoundBrackets);
			return match ? match[1] : '';
		})
		.filter((filepath) => filepath !== '');
}
