AWSTemplateFormatVersion: "2010-09-09"
Description: Create/update SalesForce cases for self service cancellation tracking

Parameters:
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - PROD
            - CODE
            - DEV
        Default: CODE

Conditions:
  CreateProdMonitoring: !Equals [ !Ref Stage, PROD ]

Mappings:
    StageMap:
        DEV:
            ApiName: cancellation-sf-cases-api-DEV
        CODE:
            ApiName: cancellation-sf-cases-api-CODE
#            DomainName: cancellation-sf-cases-api-code.membership.guardianapis.com
#            CertificateId: e4e6431e-08b9-4315-b997-75f2f9569d6c
#            ApiGatewayTargetDomainName: d-zjtpjur7zj.execute-api.eu-west-1.amazonaws.com
        PROD:
            ApiName: cancellation-sf-cases-api-PROD
#            DomainName: cancellation-sf-cases-api-prod.membership.guardianapis.com
#            CertificateId: c1e85179-09e3-4222-adee-e4ee77e73304
#            ApiGatewayTargetDomainName: d-1lv8q5nggh.execute-api.eu-west-1.amazonaws.com

Resources:
    CancellationSFCasesRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                             - lambda.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /
            Policies:
                - PolicyName: LambdaPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                            - logs:CreateLogGroup
                            - logs:CreateLogStream
                            - logs:PutLogEvents
                            - lambda:InvokeFunction
                            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/cancellation-sf-cases-*-${Stage}:log-stream:*"
                - PolicyName: ReadPrivateCredentials
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action: s3:GetObject
                            Resource: !Sub arn:aws:s3:::gu-reader-revenue-private/membership/support-service-lambdas/${Stage}/*

    CancellationSFCasesAPI:
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            Description: manage-frontend uses to create/update SalesForce cases for self service cancellation tracking
            Name: !FindInMap [StageMap, !Ref Stage, ApiName]

    CancellationSFRaiseCasePermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:invokeFunction
            FunctionName: !Sub cancellation-sf-cases-raise-${Stage}
            Principal: apigateway.amazonaws.com
        DependsOn: CancellationSFRaiseCaseLambda

    CancellationSFRaiseCaseLambda:
        Type: AWS::Lambda::Function
        Properties:
            Description: manage-frontend used to create SalesForce cases for self service cancellation tracking
            FunctionName:
                !Sub cancellation-sf-cases-raise-${Stage}
            Code:
                S3Bucket: support-service-lambdas-dist
                S3Key: !Sub subscriptions/${Stage}/cancellation-sf-cases/cancellation-sf-cases.jar
            Handler: com.gu.cancellation.sf_cases.Handler::raiseCase
            Environment:
                Variables:
                  Stage: !Ref Stage
            Role:
                Fn::GetAtt:
                - "CancellationSFCasesRole"
                - Arn
            MemorySize: 1536
            Runtime: java8
            Timeout: 300
        DependsOn:
        - "CancellationSFCasesRole"

    CancellationSFCaseProxyResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref CancellationSFCasesAPI
            ParentId: !GetAtt [CancellationSFCasesAPI, RootResourceId]
            PathPart: case
        DependsOn: CancellationSFCasesAPI

    CancellationSFRaiseCaseMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            ApiKeyRequired: false
            RestApiId: !Ref CancellationSFCasesAPI
            ResourceId: !Ref CancellationSFCaseProxyResource
            HttpMethod: POST
            Integration:
              Type: AWS_PROXY
              IntegrationHttpMethod: POST # this for the interaction between API Gateway and Lambda and MUST be POST
              Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CancellationSFRaiseCaseLambda.Arn}/invocations
        DependsOn:
        - CancellationSFCasesAPI
        - CancellationSFRaiseCaseLambda
        - CancellationSFCaseProxyResource

    CancellationSFUpdateCasePermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:invokeFunction
            FunctionName: !Sub cancellation-sf-cases-update-${Stage}
            Principal: apigateway.amazonaws.com
        DependsOn: CancellationSFUpdateCaseLambda

    CancellationSFUpdateCaseLambda:
        Type: AWS::Lambda::Function
        Properties:
            Description: manage-frontend used to update SalesForce cases for self service cancellation tracking
            FunctionName:
                !Sub cancellation-sf-cases-update-${Stage}
            Code:
                S3Bucket: support-service-lambdas-dist
                S3Key: !Sub subscriptions/${Stage}/cancellation-sf-cases/cancellation-sf-cases.jar
            Handler: com.gu.cancellation.sf_cases.Handler::updateCase
            Environment:
                Variables:
                  Stage: !Ref Stage
            Role:
                Fn::GetAtt:
                - "CancellationSFCasesRole"
                - Arn
            MemorySize: 1536
            Runtime: java8
            Timeout: 300
        DependsOn:
        - "CancellationSFCasesRole"

    CancellationSFUpdateCaseProxyResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref CancellationSFCasesAPI
            ParentId: !Ref CancellationSFCaseProxyResource
            PathPart: "{caseId}"
        DependsOn: CancellationSFCasesAPI

    CancellationSFUpdateCaseMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            AuthorizationType: NONE
            ApiKeyRequired: false
            RestApiId: !Ref CancellationSFCasesAPI
            ResourceId: !Ref CancellationSFUpdateCaseProxyResource
            HttpMethod: PATCH
            RequestParameters:
              method.request.path.caseId: true
            Integration:
              Type: AWS_PROXY
              IntegrationHttpMethod: POST # this for the interaction between API Gateway and Lambda and MUST be POST
              Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CancellationSFUpdateCaseLambda.Arn}/invocations
        DependsOn:
        - CancellationSFCasesAPI
        - CancellationSFUpdateCaseLambda
        - CancellationSFUpdateCaseProxyResource

    CancellationSFCasesAPIStage:
        Type: AWS::ApiGateway::Stage
        Properties:
            Description: Stage for cancellation-sf-cases-api
            RestApiId: !Ref CancellationSFCasesAPI
            DeploymentId: !Ref CancellationSFCasesAPIDeployment
            StageName: !Sub ${Stage}
        DependsOn:
        - CancellationSFRaiseCaseMethod
        - CancellationSFUpdateCaseMethod

    CancellationSFCasesAPIDeployment:
        Type: AWS::ApiGateway::Deployment
        Properties:
            Description: Deploys cancellation-sf-cases-api into an environment/stage
            RestApiId: !Ref CancellationSFCasesAPI
        DependsOn:
        - CancellationSFRaiseCaseMethod
        - CancellationSFUpdateCaseMethod

#    CancellationSFCasesUsagePlan:
#      Type: "AWS::ApiGateway::UsagePlan"
#      Properties:
#        UsagePlanName: !Sub cancellation-sf-cases-api-usage-plan-${Stage}
#        ApiStages:
#        - ApiId: !Ref CancellationSFCasesAPI
#          Stage: !Ref CancellationSFCasesAPIStage
#      DependsOn:
#      - CancellationSFCasesAPI
#      - CancellationSFCasesAPIStage
#
#    CancellationSFCasesUsagePlanKey:
#      Type: "AWS::ApiGateway::UsagePlanKey"
#      Properties:
#        KeyId: !Ref CancellationSFCasesAPIKey
#        KeyType: API_KEY
#        UsagePlanId: !Ref CancellationSFCasesUsagePlan
#      DependsOn:
#      - CancellationSFCasesAPIKey
#      - CancellationSFCasesUsagePlan

#    CancellationSFCasesDomainName:
#      Type: "AWS::ApiGateway::DomainName"
#      Properties:
#        RegionalCertificateArn: !Sub
#        - arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${CertificateId}
#        - { CertificateId: !FindInMap [ StageMap, !Ref Stage, CertificateId ] }
#        DomainName: !FindInMap [ StageMap, !Ref Stage, DomainName ]
#        EndpointConfiguration:
#          Types:
#            - REGIONAL

#    CancellationSFCasesBasePathMapping:
#      Type: "AWS::ApiGateway::BasePathMapping"
#      Properties:
#        RestApiId: !Ref CancellationSFCasesAPI
#        DomainName: !Ref CancellationSFCasesDomainName
#        Stage: !Sub ${Stage}
#      DependsOn:
#      - CancellationSFCasesAPI
#      - CancellationSFCasesDomainName

#    CancellationSFCasesDNSRecord:
#      Type: AWS::Route53::RecordSet
#      Properties:
#        HostedZoneName: membership.guardianapis.com.
#        Name: !FindInMap [ StageMap, !Ref Stage, DomainName ]
#        Comment: !Sub CNAME for cancellation-sf-cases API ${Stage}
#        Type: CNAME
#        TTL: '120'
#        ResourceRecords:
#        - !FindInMap [ StageMap, !Ref Stage, ApiGatewayTargetDomainName ]

    5xxApiAlarm:
      Type: AWS::CloudWatch::Alarm
      Condition: CreateProdMonitoring
      Properties:
        AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:fulfilment-dev
        AlarmName:
          !Sub
            - 5XX rate from ${ApiName}
            - { ApiName: !FindInMap [StageMap, !Ref Stage, ApiName] }
        ComparisonOperator: GreaterThanThreshold
        Dimensions:
          - Name: ApiName
            Value: !FindInMap [StageMap, !Ref Stage, ApiName]
          - Name: Stage
            Value: !Sub ${Stage}
        EvaluationPeriods: 1
        MetricName: 5XXError
        Namespace: AWS/ApiGateway
        Period: 3600
        Statistic: Sum
        Threshold: 5
        TreatMissingData: notBreaching