stacks:
- membership
regions:
- eu-west-1
deployments:
  new-product-api-cloudformation:
    type: cloud-formation
    app: new-product-api
    parameters:
      templateStagePaths:
        CODE: new-product-api-CODE.template.json
        PROD: new-product-api-PROD.template.json

  new-product-api:
    type: aws-lambda
    parameters:
      fileName: new-product-api.jar
      bucket: support-service-lambdas-dist
      prefixStack: false
      functionNames:
      - add-subscription-
      - product-catalog-
    dependencies: [new-product-api-cloudformation]
