Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
    Default: CODE

Mappings:
  StageMap:
    CODE:
      SecretsVersion: "9a7414c9-6711-44fa-a683-b1d11643c8c7"
    PROD:
      SecretsVersion: "0cee634d-a5f4-454d-a3a2-9d57ee90e154"

Resources:
  ContactUsApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Stage}
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: !Sub contact-us-api-${Stage}-UsagePlan
          Description: !Sub Usage plan for contact-us-api-${Stage}

  ContactUsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub contact-us-api-${Stage}
      Handler: com.gu.contact_us_api.Handler
      Runtime: java8
      CodeUri:
        Bucket: support-service-lambdas-dist
        Key: !Sub membership/${Stage}/contact-us-api/contact-us-api.jar
      Timeout: 120
      MemorySize: 256
      Environment:
        Variables:
          clientID:
            !Sub
            - '{{resolve:secretsmanager:contact-us-api-${Stage}:SecretString:clientID::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [ StageMap, !Ref Stage, SecretsVersion ]
          clientSecret:
            !Sub
            - '{{resolve:secretsmanager:contact-us-api-${Stage}:SecretString:clientSecret::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [ StageMap, !Ref Stage, SecretsVersion ]
          username:
            !Sub
            - '{{resolve:secretsmanager:contact-us-api-${Stage}:SecretString:username::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [ StageMap, !Ref Stage, SecretsVersion ]
          password:
            !Sub
            - '{{resolve:secretsmanager:contact-us-api-${Stage}:SecretString:password::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [ StageMap, !Ref Stage, SecretsVersion ]
          token:
            !Sub
            - '{{resolve:secretsmanager:contact-us-api-${Stage}:SecretString:token::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [ StageMap, !Ref Stage, SecretsVersion ]
          authDomain:
            !Sub
            - '{{resolve:secretsmanager:contact-us-api-${Stage}:SecretString:authDomain::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [ StageMap, !Ref Stage, SecretsVersion ]
          reqDomain:
            !Sub
            - '{{resolve:secretsmanager:contact-us-api-${Stage}:SecretString:reqDomain::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [ StageMap, !Ref Stage, SecretsVersion ]
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId:
              Ref: ContactUsApiGateway
