Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
      - DEV
    Default: CODE

Conditions:
  IsProd: !Equals [ !Ref Stage, PROD ]

Mappings:
  StageMap:
    PROD:
      authDomain: gnmtouchpoint.my.salesforce.com
      reqDomain: gnmtouchpoint.my.salesforce.com
      SecretsVersion: cfe10466-bd62-45f2-a61f-3fcf9c12ef9f
    CODE:
      authDomain: test.salesforce.com
      reqDomain: gnmtouchpoint--DEV.my.salesforce.com
      SecretsVersion: 5a68b23e-6d75-4bb4-9131-a4d94c121010
    DEV:
      authDomain: test.salesforce.com
      reqDomain: gnmtouchpoint--DEV.my.salesforce.com
      SecretsVersion: 89ac830e-166c-444a-a61b-72fb5173e761

Resources:
  ContactUsApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub contact-us-api-${Stage}-ApiGateway
      StageName: !Sub ${Stage}
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: !Sub contact-us-api-${Stage}-UsagePlan
          Description: !Sub Usage plan for contact-us-api-${Stage}

  ContactUsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub contact-us-api-${Stage}
      Handler: com.gu.contact_us_api.Handler
      Runtime: java8
      CodeUri:
        Bucket: support-service-lambdas-dist
        Key: !Sub membership/${Stage}/contact-us-api/contact-us-api.jar
      Timeout: 120
      MemorySize: 256
      Environment:
        Variables:
          clientID:
            !Sub
            - '{{resolve:secretsmanager:${Stage}/Salesforce/MembersDataApi:SecretString:clientId::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [ StageMap, !Ref Stage, SecretsVersion ]
          clientSecret:
            !Sub
            - '{{resolve:secretsmanager:${Stage}/Salesforce/MembersDataApi:SecretString:clientSecret::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [ StageMap, !Ref Stage, SecretsVersion ]
          username:
            !Sub
            - '{{resolve:secretsmanager:${Stage}/Salesforce/MembersDataApi:SecretString:userName::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [ StageMap, !Ref Stage, SecretsVersion ]
          password:
            !Sub
            - '{{resolve:secretsmanager:${Stage}/Salesforce/MembersDataApi:SecretString:password::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [ StageMap, !Ref Stage, SecretsVersion ]
          token:
            !Sub
            - '{{resolve:secretsmanager:${Stage}/Salesforce/MembersDataApi:SecretString:token::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [ StageMap, !Ref Stage, SecretsVersion ]
          authDomain: !FindInMap [ StageMap, !Ref Stage, authDomain ]
          reqDomain: !FindInMap [ StageMap, !Ref Stage, reqDomain ]
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId:
              Ref: ContactUsApiGateway

  4xxApiAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    DependsOn:
      - ContactUsApiGateway
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:fulfilment-dev
      AlarmName: !Sub 4XX rate from contact-us-api-${Stage}
      AlarmDescription: >
        See https://github.com/guardian/support-service-lambdas/blob/main/handlers/contact-us-api/README.md#4XX-Errors
        for possible causes, impacts and fixes.
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub membership-${Stage}-contact-us-api
        - Name: Stage
          Value: !Sub ${Stage}
      EvaluationPeriods: 1
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Period: 3600
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  5xxApiAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    DependsOn:
      - ContactUsApiGateway
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:fulfilment-dev
      AlarmName: !Sub 5XX rate from contact-us-api-${Stage}
      AlarmDescription: >
        See https://github.com/guardian/support-service-lambdas/blob/main/handlers/contact-us-api/README.md#5XX-Errors
        for possible causes, impacts and fixes.
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub membership-${Stage}-contact-us-api
        - Name: Stage
          Value: !Sub ${Stage}
      EvaluationPeriods: 1
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Period: 3600
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
