Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
      - DEV
    Default: CODE

Conditions:
  IsProd: !Equals [ !Ref Stage, PROD ]

Mappings:
  StageMap:
    PROD:
      authDomain: gnmtouchpoint.my.salesforce.com
      reqDomain: gnmtouchpoint.my.salesforce.com
      SalesforceStage: PROD
      AppName: TouchpointUpdate
      AppSecretsVersion: d338b761-cb81-4adf-aca4-163678e65a59
      UserSecretsVersion: dfbf9eba-5215-4cb8-91f1-ff5bcbbf5201
    CODE:
      authDomain: test.salesforce.com
      reqDomain: gnmtouchpoint--DEV1.my.salesforce.com
      SalesforceStage: DEV
      AppName: AwsConnectorSandbox
      AppSecretsVersion: b7b63e09-f39f-4e4f-80ef-9dd203c2d59b
      UserSecretsVersion: 4a0eabf6-7940-47ef-87d0-36c3ef7f5741
    DEV:
      authDomain: test.salesforce.com
      reqDomain: gnmtouchpoint--DEV1.my.salesforce.com
      SalesforceStage: DEV
      AppName: AwsConnectorSandbox
      AppSecretsVersion: b7b63e09-f39f-4e4f-80ef-9dd203c2d59b
      UserSecretsVersion: 4a0eabf6-7940-47ef-87d0-36c3ef7f5741

Resources:
  ContactUsApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: '2.0'
      Name: !Sub contact-us-api-${Stage}-ApiGateway
      StageName: !Sub ${Stage}
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: !Sub contact-us-api-${Stage}-UsagePlan
          Description: !Sub Usage plan for contact-us-api-${Stage}

  ContactUsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub contact-us-api-${Stage}
      Handler: com.gu.contact_us_api.Handler
      Runtime: java8.al2
      CodeUri:
        Bucket: support-service-lambdas-dist
        Key: !Sub membership/${Stage}/contact-us-api/contact-us-api.jar
      Timeout: 120
      MemorySize: 256
      Environment:
        Variables:
          clientID:
            !Sub
            - '{{resolve:secretsmanager:${SalesforceStage}/Salesforce/ConnectedApp/${AppName}:SecretString:clientId::${AppSecretsVersion}}}'
            - SalesforceStage: !FindInMap [ StageMap, !Ref Stage, SalesforceStage ]
              AppName: !FindInMap [ StageMap, !Ref Stage, AppName ]
              AppSecretsVersion: !FindInMap [ StageMap, !Ref Stage, AppSecretsVersion ]
          clientSecret:
            !Sub
            - '{{resolve:secretsmanager:${SalesforceStage}/Salesforce/ConnectedApp/${AppName}:SecretString:clientSecret::${AppSecretsVersion}}}'
            - SalesforceStage: !FindInMap [ StageMap, !Ref Stage, SalesforceStage ]
              AppName: !FindInMap [ StageMap, !Ref Stage, AppName ]
              AppSecretsVersion: !FindInMap [ StageMap, !Ref Stage, AppSecretsVersion ]
          username:
            !Sub
            - '{{resolve:secretsmanager:${SalesforceStage}/Salesforce/User/MembersDataAPI:SecretString:username::${UserSecretsVersion}}}'
            - SalesforceStage: !FindInMap [ StageMap, !Ref Stage, SalesforceStage ]
              UserSecretsVersion: !FindInMap [ StageMap, !Ref Stage, UserSecretsVersion ]
          password:
            !Sub
            - '{{resolve:secretsmanager:${SalesforceStage}/Salesforce/User/MembersDataAPI:SecretString:password::${UserSecretsVersion}}}'
            - SalesforceStage: !FindInMap [ StageMap, !Ref Stage, SalesforceStage ]
              UserSecretsVersion: !FindInMap [ StageMap, !Ref Stage, UserSecretsVersion ]
          token:
            !Sub
            - '{{resolve:secretsmanager:${SalesforceStage}/Salesforce/User/MembersDataAPI:SecretString:token::${UserSecretsVersion}}}'
            - SalesforceStage: !FindInMap [ StageMap, !Ref Stage, SalesforceStage ]
              UserSecretsVersion: !FindInMap [ StageMap, !Ref Stage, UserSecretsVersion ]
          authDomain: !FindInMap [ StageMap, !Ref Stage, authDomain ]
          reqDomain: !FindInMap [ StageMap, !Ref Stage, reqDomain ]
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId:
              Ref: ContactUsApiGateway

  4xxApiAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    DependsOn:
      - ContactUsApiGateway
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:fulfilment-dev
      AlarmName: !Sub 4XX rate from contact-us-api-${Stage}
      AlarmDescription: >
        See https://github.com/guardian/support-service-lambdas/blob/main/handlers/contact-us-api/README.md#4XX-Errors
        for possible causes, impacts and fixes.
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub contact-us-api-${Stage}-ApiGateway
        - Name: Stage
          Value: !Sub ${Stage}
      EvaluationPeriods: 1
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Period: 3600
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  5xxApiAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    DependsOn:
      - ContactUsApiGateway
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:fulfilment-dev
      AlarmName: !Sub 5XX rate from contact-us-api-${Stage}
      AlarmDescription: >
        See https://github.com/guardian/support-service-lambdas/blob/main/handlers/contact-us-api/README.md#5XX-Errors
        for possible causes, impacts and fixes.
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub contact-us-api-${Stage}-ApiGateway
        - Name: Stage
          Value: !Sub ${Stage}
      EvaluationPeriods: 1
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Period: 3600
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  noRequestsAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    DependsOn:
      - ContactUsApiGateway
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:fulfilment-dev
      AlarmName: !Sub No requests coming into contact-us-api-${Stage}
      AlarmDescription: >
        This is a last line catch-all alarm. It means no requests were received in the last 6 hours.
        It might mean something's (silently) gone wrong with a part of the system that sends these requests (eg. MMA client or server-side).
        Or it could mean our users are happy and don't need to contact us. :)
      ComparisonOperator: LessThanThreshold
      Threshold: 1
      EvaluationPeriods: 6
      Metrics:
        - Id: actualCount
          Expression: "FILL(rawCount, 0)"
        - Id: rawCount
          ReturnData: false
          MetricStat:
            Metric:
              MetricName: Count
              Namespace: AWS/ApiGateway
              Dimensions:
                - Name: ApiName
                  Value: !Sub contact-us-api-${Stage}-ApiGateway
                - Name: Stage
                  Value: !Sub ${Stage}
            Period: 3600
            Stat: Sum
            Unit: Count
      TreatMissingData: breaching
