Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
    Default: CODE

Conditions:
  IsProd: !Equals [ !Ref Stage, PROD ]

Mappings:
  StageMap:
    PROD:
      authDomain: gnmtouchpoint.my.salesforce.com
      reqDomain: gnmtouchpoint.my.salesforce.com
      SalesforceStage: PROD
      AppName: TouchpointUpdate
      AppSecretsVersion: d338b761-cb81-4adf-aca4-163678e65a59
      UserSecretsVersion: dfbf9eba-5215-4cb8-91f1-ff5bcbbf5201
    CODE:
      authDomain: test.salesforce.com
      reqDomain: gnmtouchpoint--DEV1.sandbox.my.salesforce.com
      SalesforceStage: CODE
      AppName: AwsConnectorSandbox
      AppSecretsVersion: abaa595b-e6c8-4d13-81e0-2d02627536c7
      UserSecretsVersion: 4a0eabf6-7940-47ef-87d0-36c3ef7f5741

Resources:

  ContactUsApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: '2.0'
      Name: !Sub contact-us-api-${Stage}-ApiGateway
      StageName: !Sub ${Stage}
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: !Sub contact-us-api-${Stage}-UsagePlan
          Description: !Sub Usage plan for contact-us-api-${Stage}

  ContactUsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Tags:
        - Key: App
          Value: contact-us-api
        - Key: Stage
          Value:
            Ref: Stage
        - Key: Stack
          Value: membership
      Path: /
      Policies:
        - PolicyName: ContactUsLambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/contact-us-api-${Stage}:log-stream:*
        - PolicyName: ReadFromSecretsManagerPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetSecretValue
                Resource:
                  - Fn::Sub:
                      - "arn:aws:secretsmanager:eu-west-1:865473395570:secret:${SalesforceStage}/Salesforce/ConnectedApp/${AppName}"
                      - SalesforceStage: !FindInMap [StageMap, !Ref Stage, SalesforceStage]
                        AppName: !FindInMap [StageMap, !Ref Stage, AppName]
                  - Fn::Sub:
                      - "arn:aws:secretsmanager:eu-west-1:865473395570:secret:${SalesforceStage}/Salesforce/User/MembersDataAPI"
                      - SalesforceStage: !FindInMap [StageMap, !Ref Stage, SalesforceStage]

  ContactUsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub contact-us-api-${Stage}
      Handler: com.gu.contact_us_api.Handler
      Runtime: java11
      CodeUri:
        Bucket: support-service-lambdas-dist
        Key: !Sub membership/${Stage}/contact-us-api/contact-us-api.jar
      Timeout: 60
      MemorySize: 1024
      Environment:
        Variables:
          stage: !Ref Stage
          authDomain: !FindInMap [ StageMap, !Ref Stage, authDomain ]
          reqDomain: !FindInMap [ StageMap, !Ref Stage, reqDomain ]
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId:
              Ref: ContactUsApiGateway
      Role:
        Fn::GetAtt:
          - "ContactUsLambdaRole"
          - Arn
    DependsOn:
      - ContactUsLambdaRole

  4xxApiAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    DependsOn:
      - ContactUsApiGateway
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:retention-dev
      AlarmName: !Sub 4XX rate from contact-us-api-${Stage}
      AlarmDescription: >
        See https://github.com/guardian/support-service-lambdas/blob/main/handlers/contact-us-api/README.md#4XX-Errors
        for possible causes, impacts and fixes.
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub contact-us-api-${Stage}-ApiGateway
        - Name: Stage
          Value: !Sub ${Stage}
      EvaluationPeriods: 1
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Period: 3600
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  5xxApiAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    DependsOn:
      - ContactUsApiGateway
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:retention-dev
      AlarmName: !Sub 5XX rate from contact-us-api-${Stage}
      AlarmDescription: >
        See https://github.com/guardian/support-service-lambdas/blob/main/handlers/contact-us-api/README.md#5XX-Errors
        for possible causes, impacts and fixes.
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub contact-us-api-${Stage}-ApiGateway
        - Name: Stage
          Value: !Sub ${Stage}
      EvaluationPeriods: 1
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Period: 3600
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  noRequestsAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    DependsOn:
      - ContactUsApiGateway
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:retention-dev
      AlarmName: !Sub No requests coming into contact-us-api-${Stage}
      AlarmDescription: >
        This is a last line catch-all alarm. It means no requests were received in the last 6 hours.
        It might mean something's (silently) gone wrong with a part of the system that sends these requests (eg. MMA client or server-side).
        Or it could mean our users are happy and don't need to contact us. :)
      ComparisonOperator: LessThanThreshold
      Threshold: 1
      EvaluationPeriods: 12
      Metrics:
        - Id: actualCount
          Expression: "FILL(rawCount, 0)"
        - Id: rawCount
          ReturnData: false
          MetricStat:
            Metric:
              MetricName: Count
              Namespace: AWS/ApiGateway
              Dimensions:
                - Name: ApiName
                  Value: !Sub contact-us-api-${Stage}-ApiGateway
                - Name: Stage
                  Value: !Sub ${Stage}
            Period: 3600
            Stat: Sum
            Unit: Count
      TreatMissingData: breaching
