stacks:
  - membership
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  cfn:
    type: cloud-formation
    app: holiday-stop-processor
    parameters:
      templatePath: cfn.yaml
  holiday-stop-processor:
    type: aws-lambda
    parameters:
      fileName: holiday-stop-processor.jar
      bucket: support-service-lambdas-dist
      prefixStack: false
      functionNames:
        - holiday-stop-processor-
    dependencies: [cfn]
