stacks:
  - membership
regions:
  - eu-west-1
allowedStages:
  - CODE
  - PROD
deployments:
  holiday-stop-processor-cloudformation:
    type: cloud-formation
    app: holiday-stop-processor
    parameters:
      templateStagePaths:
        CODE: ./cdk/cdk.out/holiday-stop-processor-CODE.template.json
        PROD: ./cdk/cdk.out/holiday-stop-processor-PROD.template.json
  holiday-stop-processor:
    type: aws-lambda
    parameters:
      fileName: holiday-stop-processor.jar
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
        - holiday-stop-processor-
    dependencies: [holiday-stop-processor-cloudformation]
