stacks:
  - membership
regions:
  - eu-west-1
allowedStages:
  - CODE
  - CSBX
  - PROD
deployments:
  salesforce-disaster-recovery-cloudformation:
    type: cloud-formation
    app: salesforce-disaster-recovery
    parameters:
      templateStagePaths:
        CODE: salesforce-disaster-recovery-CODE.template.json
        CSBX: salesforce-disaster-recovery-CSBX.template.json
        PROD: salesforce-disaster-recovery-PROD.template.json
  salesforce-disaster-recovery:
    type: aws-lambda
    parameters:
      fileName: salesforce-disaster-recovery.zip
      bucketSsmLookup: true
      prefixStack: false
      functionNames:
        - save-failed-rows-to-s3-
        - save-salesforce-query-result-to-s3-
        - update-zuora-accounts-
        - send-completion-notification-2-
    dependencies: [salesforce-disaster-recovery-cloudformation]
