name: CI-Scala
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

# Ensure we only ever have one build running at a time.
# If we push twice in quick succession, the first build will be stopped once the second starts.
# This avoids multiple deploys happening in quick succession causing AWS rate exceeded errors.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gu-cdk-build:
    strategy:
      fail-fast: false
      matrix:
        subproject:
          - batch-email-sender
          - cancellation-sf-cases-api
          - new-product-api
          - single-contribution-salesforce-writes
          - stripe-webhook-endpoints
          - soft-opt-in-consent-setter
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'sbt'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Run tests and build subproject JAR
        run: sbt "project ${{ matrix.subproject }}" test assembly
      - run: npm install --global corepack@0.31.0
      - run: corepack enable
        shell: bash
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm --filter cdk package

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4.3.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          projectName: support-service-lambdas::${{ matrix.subproject }}
          buildNumberOffset: 7000
          configPath: ./handlers/${{ matrix.subproject }}/riff-raff.yaml
          commentingEnabled: 'false'
          contentDirectories: |
            ${{ matrix.subproject }}-cloudformation:
              - ./cdk/cdk.out/${{ matrix.subproject }}-CODE.template.json
              - ./cdk/cdk.out/${{ matrix.subproject }}-PROD.template.json
            ${{ matrix.subproject }}:
              - ./handlers/${{ matrix.subproject }}/target/scala-2.13/${{ matrix.subproject }}.jar
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - subproject: catalog-service
            scala-version: 2.13
          - subproject: contact-us-api
            scala-version: 2.13
          - subproject: delivery-problem-credit-processor
            scala-version: 2.13
          - subproject: delivery-records-api
            scala-version: 2.13
          - subproject: dev-env-cleaner
            scala-version: 2.13
          - subproject: digital-subscription-expiry
            scala-version: 2.13
          - subproject: digital-voucher-api
            scala-version: 2.13
          - subproject: digital-voucher-cancellation-processor
            scala-version: 2.13
          - subproject: digital-voucher-suspension-processor
            scala-version: 2.13
          - subproject: fulfilment-date-calculator
            scala-version: 2.13
          - subproject: holiday-stop-api
            scala-version: 2.13
          - subproject: holiday-stop-processor
            scala-version: 2.13
          - subproject: identity-backfill
            scala-version: 2.13
          - subproject: identity-retention
            scala-version: 2.13
          - subproject: product-move-api
            scala-version: 3.7.2
          - subproject: sf-api-user-credentials-setter
            scala-version: 2.13
          - subproject: sf-contact-merge
            scala-version: 2.13
          - subproject: sf-datalake-export
            scala-version: 2.13
          - subproject: sf-emails-to-s3-exporter
            scala-version: 2.13
          - subproject: sf-gocardless-sync
            scala-version: 2.13
          - subproject: sf-move-subscriptions-api
            scala-version: 2.13
          - subproject: zuora-datalake-export
            scala-version: 2.13
          - subproject: zuora-rer
            scala-version: 2.13
          - subproject: zuora-sar
            scala-version: 2.13
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'sbt'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Build
        run: |
          LAST_TEAMCITY_BUILD=6410
          export GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))
          sbt "project ${{ matrix.subproject }}" assembly

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4.3.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          projectName: support-service-lambdas::${{ matrix.subproject }}
          buildNumberOffset: 6410
          configPath: ./handlers/${{ matrix.subproject }}/riff-raff.yaml
          commentingEnabled: 'false'
          contentDirectories: |
            ${{ matrix.subproject }}:
              - ./handlers/${{ matrix.subproject }}/target/scala-${{ matrix.scala-version }}/${{ matrix.subproject }}.jar


  zuora-callout-apis:
    name: build (zuora-callout-apis)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'sbt'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Run tests and build subproject JAR
        run: sbt "project zuora-callout-apis" test assembly

      - run: npm install --global corepack@0.31.0
      - run: corepack enable
        shell: bash
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm --filter cdk package

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4.3.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          projectName: support-service-lambdas::zuora-callout-apis
          buildNumberOffset: 7000
          configPath: ./handlers/zuora-callout-apis/riff-raff.yaml
          commentingEnabled: 'false'
          contentDirectories: |
            zuora-auto-cancel-upload:
              - ./handlers/zuora-callout-apis/target/scala-2.13/zuora-callout-apis.jar
            zuora-auto-cancel-cloudformation:
              - ./cdk/cdk.out/zuora-auto-cancel-CODE.template.json
              - ./cdk/cdk.out/zuora-auto-cancel-PROD.template.json
            zuora-callout-apis:
              - ./handlers/zuora-callout-apis/target/scala-2.13/zuora-callout-apis.jar
