name: build-single-contribution-record-app

on:
  push:
    paths:
      - "cdk/**"
      - ".github/workflows/ci-single-contribution-record.yml"

jobs:
  build-single-contribution-record-app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
