name: CI-Typescript
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

# Ensure we only ever have one build running at a time.
# If we push twice in quick succession, the first build will be stopped once the second starts.
# This avoids multiple deploys happening in quick succession causing AWS rate exceeded errors
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  load-matrix:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      subprojects: ${{ steps.read-matrix.outputs.subprojects }}
    steps:
      - uses: actions/checkout@v6.0.1
      - id: read-matrix
        run: |
          echo "subprojects=$(jq -c '.subproject' .github/workflows/handlerNames.managed.json)" >> "$GITHUB_OUTPUT"

  gu-cdk-build:
    needs:
      - load-matrix
    strategy:
      fail-fast: false
      matrix:
        subproject: ${{ fromJson(needs.load-matrix.outputs.subprojects) }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6.0.1
      - run: npm install --global corepack@0.31.0
      - run: corepack enable
        shell: bash
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm --filter "./buildcheck" type-check
      - run: pnpm --filter "./buildcheck" check-formatting
      - run: pnpm --filter "./buildcheck" lint
      - run: pnpm --filter "./buildcheck" snapshot:assert 'ROOT|modules|handlers/${{ matrix.subproject }}'
      - run: pnpm --filter cdk package ${{ matrix.subproject }}
      - run: pnpm --filter ${{ matrix.subproject }}... --parallel --aggregate-output '/^(type-check|lint|check-formatting)$/'
      - run: pnpm --filter ${{ matrix.subproject }}... test
      - run: pnpm --filter ${{ matrix.subproject }} packageQuick

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4.3.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          projectName: support-service-lambdas::${{ matrix.subproject }}
          buildNumberOffset: 7000
          configPath: ./handlers/${{ matrix.subproject }}/riff-raff.yaml
          commentingEnabled: 'false'
          contentDirectories: |
            ${{ matrix.subproject }}-cloudformation:
              - ./cdk/cdk.out/${{ matrix.subproject }}-CODE.template.json
              - ./cdk/cdk.out/${{ matrix.subproject }}-PROD.template.json
            ${{ matrix.subproject }}:
              - ./handlers/${{ matrix.subproject }}/target/${{ matrix.subproject }}.zip

  # for branch protection - only passes if all builds pass
  ci-typescript-all:
    name: ci-typescript-all
    runs-on: ubuntu-latest
    permissions: {}
    if: ${{ always() }}
    needs:
      - gu-cdk-build
    steps:
      - name: Fail unless all matrix jobs succeeded
        run: |
          [ "${{ needs.gu-cdk-build.result }}" = "success" ]

