name: Build failed-national-deliveries-processor

on:
  - push

jobs:
  CI:
    if: github.repository_owner == 'guardian'
    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read
    name: failed-national-deliveries-processor build
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'handlers/failed-national-deliveries-processor/.nvmrc'
          cache: 'yarn'
          cache-dependency-path: handlers/failed-national-deliveries-processor/yarn.lock

      - name: Yarn
        run: |
          yarn install
          yarn run build
        working-directory: handlers/failed-national-deliveries-processor

      - name: Copy files to Riff Raff package
        run: cp package.json riff-raff.yaml dist
        working-directory: handlers/failed-national-deliveries-processor

      - name: Zip target directory contents (quietly)
        run: zip -qr ../failed-national-deliveries-processor.zip ./*
        working-directory: handlers/failed-national-deliveries-processor/dist

      - name: Yarn (CDK)
        working-directory: cdk
        run: |
          yarn install
          yarn tsc
          yarn lint
          yarn test

      - name: Yarn synth (CDK)
        working-directory: cdk
        run: yarn synth

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v2
        with:
          projectName: 'support-service-lambdas::failed-national-deliveries-processor'
          app: failed-national-deliveries-processor
          configPath: handlers/failed-national-deliveries-processor/riff-raff.yaml
          contentDirectories: |
            cloudformation:
              - ./cdk/cdk.out/failed-national-deliveries-processor-CODE.template.json
            failed-national-deliveries-processor:
              - handlers/failed-national-deliveries-processor/failed-national-deliveries-processor.zip