# This action runs Snyk Monitor every day at 6 AM and on every push to main
name: Snyk

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    env:
      SNYK_ACTION: snyk/actions/scala@0.3.0

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Update Snyk UI with current vulnerabilities
        uses: ${{ env.SNYK_ACTION }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --org=the-guardian-cuu --project-name=${{ github.repository }}

      - name: Update Github Code Scanning file with current vulnerabilities
        uses: ${{ env.SNYK_ACTION }}
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
