name: Test
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use local action
        uses: './.github/actions/update-cfn-templates'