curl --location --request POST 'https://rest.zuora.com/v1/batch-query/' \
--header 'Content-Type: application/json' \
--header "Authorization: Bearer $1" \
--data-raw '{
"format" : "csv",
"version" : "1.1",
"name" : "ExportInvoiceItemsTool",
"encrypted" : "none",
"useQueryLabels" : "true",
"dateTimeUtc" : "true",
"queries"  : [ {
    "name" : "ExportInvoiceItemsTool-all-rate-plan-charges",
    "query" : "SELECT Subscription.Name, RatePlanCharge.Name, Subscription.ContractAcceptanceDate, Subscription.ContractEffectiveDate, RatePlanCharge.BillCycleType, RatePlanCharge.TriggerEvent, RatePlanCharge.TriggerDate, RatePlanCharge.ChargedThroughDate, RatePlanCharge.ProcessedThroughDate, RatePlanCharge.UpToPeriodsType, RatePlanCharge.UpToPeriods, RatePlanCharge.BillingPeriod, RatePlanCharge.SpecificBillingPeriod, RatePlanCharge.EndDateCondition, RatePlanCharge.EffectiveStartDate, Account.BillCycleDay, RatePlan.AmendmentType, RatePlan.Name FROM RatePlanCharge WHERE Subscription.Status = '\''Active'\'' AND RatePlanCharge.CreatedDate > '\''2019-06-01'\'' AND Subscription.AutoRenew = true AND ( RatePlanCharge.Name = '\''GW Oct 18 - 1 Year - Domestic'\'' OR RatePlanCharge.Name = '\''GW Oct 18 - 3 Month - Domestic'\''  OR RatePlanCharge.Name = '\''GW Oct 18 - Annual - Domestic'\'' OR RatePlanCharge.Name = '\''GW Oct 18 - Quarterly - Domestic'\'' OR RatePlanCharge.Name = '\''GW Oct 18 - First 6 issues - Domestic'\'' OR RatePlanCharge.Name = '\''GW Oct 18 - 1 Year - ROW'\'' OR RatePlanCharge.Name = '\''GW Oct 18 - 3 Month - ROW'\'' OR RatePlanCharge.Name = '\''GW Oct 18 - Annual - ROW'\'' OR RatePlanCharge.Name = '\''GW Oct 18 - Quarterly - ROW'\'' OR RatePlanCharge.Name = '\''GW Oct 18 - First 6 issues - ROW'\'' OR RatePlanCharge.Name = '\''Zone A 1 Year'\'' OR RatePlanCharge.Name = '\''Zone A 12 Issues'\'' OR RatePlanCharge.Name = '\''Zone A 2 Years'\'' OR RatePlanCharge.Name = '\''Zone A 3 Years'\'' OR RatePlanCharge.Name = '\''Zone A 6 Issues'\'' OR RatePlanCharge.Name = '\''Zone A 6 Months'\'' OR RatePlanCharge.Name = '\''Zone A Annual'\'' OR RatePlanCharge.Name = '\''Zone A Quarterly'\'' OR RatePlanCharge.Name = '\''Zone B 1 Year'\'' OR RatePlanCharge.Name = '\''Zone B 12 Issues'\'' OR RatePlanCharge.Name = '\''Zone B 2 Years'\'' OR RatePlanCharge.Name = '\''Zone B 3 Years'\'' OR RatePlanCharge.Name = '\''Zone B 6 Issues'\'' OR RatePlanCharge.Name = '\''Zone B 6 Months'\'' OR RatePlanCharge.Name = '\''Zone B Annual'\'' OR RatePlanCharge.Name = '\''Zone B Quarterly'\'' OR RatePlanCharge.Name = '\''Zone C 1 Year'\'' OR RatePlanCharge.Name = '\''Guardian Weekly 12 Issues'\'' OR RatePlanCharge.Name = '\''Guardian Weekly 6 Issues'\'' OR RatePlanCharge.Name = '\''Zone C 6 Months'\'' OR RatePlanCharge.Name = '\''Zone C Annual'\'' OR RatePlanCharge.Name = '\''Zone C Quarterly'\'' OR RatePlanCharge.Name = '\''Monday'\'' OR RatePlanCharge.Name = '\''Tuesday'\'' OR RatePlanCharge.Name = '\''Wednesday'\'' OR RatePlanCharge.Name = '\''Thursday'\'' OR RatePlanCharge.Name = '\''Friday'\'' OR RatePlanCharge.Name = '\''Saturday'\'' OR RatePlanCharge.Name = '\''Sunday'\'' OR RatePlanCharge.Name = '\''Holiday Credit'\'') ORDER BY Subscription.Name",
    "type" : "zoqlexport"
  }]
}'