SELECT zuora_subscription.name AS subscription_name,
         invoice_number,
         amount,
         invoice_date,
         contract_acceptance_date AS customer_acceptance_date,
         zuora_rateplancharge.id AS rate_plan_charge_id,
         zuora_rateplancharge.name AS rate_plan_charge_name,
         effective_start_date,
         billing_period,
         bill_cycle_day,
         bill_cycle_type AS billing_day,
         trigger_event,
         trigger_date,
         specific_billing_period,
         specific_end_date,
         up_to_periods,
         up_to_periods_type,
         specific_billing_period
FROM zuora_invoice
JOIN zuora_invoiceitem ON zuora_invoiceitem.invoice_id=zuora_invoice.id
JOIN zuora_rateplancharge ON zuora_rateplancharge.id=zuora_invoiceitem.rate_plan_charge_id
                             AND zuora_rateplancharge.name IN (
  'GW Oct 18 - 1 Year - Domestic',
  'GW Oct 18 - 3 Month - Domestic',
  'GW Oct 18 - Annual - Domestic',
  'GW Oct 18 - Quarterly - Domestic',
  'GW Oct 18 - First 6 issues - Domestic',
  'GW Oct 18 - 1 Year - ROW',
  'GW Oct 18 - 3 Month - ROW',
  'GW Oct 18 - Annual - ROW',
  'GW Oct 18 - Quarterly - ROW',
  'GW Oct 18 - First 6 issues - ROW',
  'Zone A 1 Year',
  'Zone A 12 Issues',
  'Zone A 2 Years',
  'Zone A 3 Years',
  'Zone A 6 Issues',
  'Zone A 6 Months',
  'Zone A Annual',
  'Zone A Quarterly',
  'Zone B 1 Year',
  'Zone B 12 Issues',
  'Zone B 2 Years',
  'Zone B 3 Years',
  'Zone B 6 Issues',
  'Zone B 6 Months',
  'Zone B Annual',
  'Zone B Quarterly',
  'Zone C 1 Year',
  'Guardian Weekly 12 Issues',
  'Guardian Weekly 6 Issues',
  'Zone C 6 Months',
  'Zone C Annual',
  'Zone C Quarterly',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday'
)
JOIN zuora_rateplan ON zuora_rateplan.id=zuora_rateplancharge.rate_plan_id
JOIN zuora_subscription ON zuora_subscription.id=zuora_rateplan.subscription_id
WHERE amount > 0
ORDER BY subscription_name, invoice_number
LIMIT 10